.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Added `Bug report` and `Feature Request` issue templates
In my warehouse, I implemented a version of it
[A preview of the effect](https://github.com/whylost/vue-devui-actiontest/issues/new/choose)

chroe: Added `Bug` and `Feature` issue templates

---

packages/devui-vue/devui/time-picker/src/components/time-scroll/composables/use-time-scroll.ts
packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts

- 修改滚动条bug （拖动滚动条到顶部后出现反向滚动的问题）
- 如果组件带有时间限制 并与 绑定时间冲突的时间。优先使用限制的时间

fix(TimePicker): 修改滚动条bug和完善时间限制

---

packages/devui-vue/devui/dropdown/src/dropdown-types.ts
packages/devui-vue/devui/dropdown/src/dropdown.scss
packages/devui-vue/devui/dropdown/src/dropdown.tsx
packages/devui-vue/docs/components/dropdown/index.md

1. 根据具体需求添加自定义宽度功能，API 名称为 width

【Dropdown】添加自定义宽度的功能

---

CONTRIBUTING.md
packages/devui-vue/docs/.vitepress/config/nav.ts
packages/devui-vue/docs/CONTRIBUTING.md

docs: add doc CONTRIBUTING.md

---

.all-contributorsrc
README.md
package.json
yarn.lock

1. 使用机器人生成贡献者名单效果如下图
用法：
1. **[授权机器人](https://allcontributors.org/docs/en/bot/installation)**
2. 在 issues或者是 pr下评论 `@all-contributors please add @kagol  for code, maintenance `，[具体用法](https://allcontributors.org/docs/en/bot/usage)
2. 调整README 的标题，h1~h5的使用

Add allcontributors reboot to generate list of contributors

---

packages/devui-vue/devui/splitter/src/splitter-bar.tsx
packages/devui-vue/devui/splitter/src/splitter-pane.tsx
packages/devui-vue/docs/en-US/components/splitter/index.md

2021-12-13
1. 修复 collasped api 不起作用，重现步骤： 垂直布局 demo，初始化设置 collapsed 为 true 时，没有默认折叠效果
2021-12-19
1. 添加 splitter 英文文档
2. splitter-bar 添加展开和收起提示文字

fix(splitter): 修复 collasped api 不起作用的问题、添加英文文档

---

packages/devui-vue/devui/button/src/button.tsx
packages/devui-vue/devui/modal/src/dialog-types.ts
packages/devui-vue/devui/modal/src/modal-types.ts
packages/devui-vue/devui/modal/src/modal.tsx

fix(modal & button): dLoading 需要单独引入 & 默认点击背景可以 modal 关闭

---

packages/devui-vue/devui/panel/__tests__/panel.spec.ts

Fix(Panel): 修复了单元测试文件不通过问题

---

packages/devui-vue/devui/toast/src/hooks/use-toast-helper.ts
packages/devui-vue/devui/toast/src/toast.tsx
packages/devui-vue/docs/.vitepress/config/markdown.ts
packages/devui-vue/docs/components/card/index.md
packages/devui-vue/docs/components/pagination/index.md

- use scss preprocessor by `vitepress-theme-demoblock`, now we can use scss in docs.
- fix some css & scss error in docs when use css preprocessor.
- #58

feat: add scss preprocessor in docs && fix:(Toast)  single lifeMode bug in Toast

---

packages/devui-vue/docs/components/button/index.md

fix(button): 修复文档中存在的问题

---

packages/devui-vue/devui/popover/__tests__/popover.spec.ts
packages/devui-vue/devui/popover/src/popover.tsx
packages/devui-vue/docs/components/popover/index.md
packages/devui-vue/docs/en-US/components/popover/index.md

* Popover增加controlled属性
* 文档增加手动触发demo

Popover增加controlled属性

---

packages/devui-vue/devui/form/src/directive/d-validate-rules.ts
packages/devui-vue/devui/form/src/form-control/form-control.tsx

fix: 
- 修复updateOn为change时，popover闪一下问题
- 修复提交验证失效问题

fix(Form): 修复一些bug

---

packages/devui-vue/devui/tag/__tests__/tag.spec.ts

feat(tag): 补充组件单元测试

---

packages/devui-vue/devui/tag/src/hooks/use-class.ts
packages/devui-vue/devui/tag/src/tag.scss

fix(tag): 修复关闭icon没有垂直居中的bug

---

packages/devui-vue/docs/.vitepress/devui-theme/styles/layout.scss

docs: 优化文档中表格的样式

---

.prettierrc

Update:
1. 将`.prerrierrc`配置的`semi `改成`true`，解决与`eslintrc.js`配置冲突的问题 #29

chore: 修改.prerrierrc配置统一加上句尾分号

---

packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/input/src/input.tsx

修改问题: [issues:密码框切换明暗文切换后, 右侧icon图标不显示](https://github.com/DevCloudFE/vue-devui/issues/194)

fix: [问题修改]密码输入框右侧图标在特定场景下不显示问题

---

packages/devui-vue/docs/.vitepress/config/nav.ts

用途：devui-playground可以用来编写组件demo，查看demo组件的编译结果，可以用来复现bug，分享给他人查看。
叫Playground即可，不需要中文名字。

feat(site): add devui playground

---

.github/workflows/pull-request.yml
.npmrc
README.md

Update:
1. 更新`README`，将`yarn`改成`pnpm`
2. 调整`pull-request.yml`，增加`pnpm`的安装

docs: update README

---

package.json
packages/devui-cli/package.json
packages/devui-cli/src/bin.ts
packages/devui-cli/src/commands/base.ts
packages/devui-cli/src/shared/config.ts
packages/devui-cli/src/shared/utils.ts
packages/devui-cli/src/templates/base/config.ts
packages/devui-cli/src/templates/component/utils.ts
packages/devui-cli/src/templates/lib-entry/lib-entry.ts
packages/devui-cli/tsconfig.json
packages/devui-vue/dc.config.ts
packages/devui-vue/package.json
pnpm-lock.yaml

- 修复配置文件未设置 cwd 选项时空指针异常问题
- 修复库入口生成时查询组件失败问题
- 修复生成的 dts 目录结构错误
- 修复动态读取配置文件时加载失败问题
- 移除生成 dts 命令

fix: 修复 devui-cli

---

packages/devui-vue/dc.config.ts
packages/devui-vue/package.json
pnpm-lock.yaml

增加脚本命令`cli`，该命令可使用`devui-cli`的能力创建组件模板和入口文件。
使用方式：
```shell
pnpm cli --filter vue-devui
```

build: add script cli

---

packages/devui-vue/devui/drawer/src/drawer-service.tsx

Update:
1. `lodash-es` -> `lodash`，修复`pnpm build`构建错误
```
✖ rendering pages...
build error:
Error [ERR_REQUIRE_ESM]: require() of ES Module vue-devui\node_modules\.pnpm\lodash-es@4.17.21\node_modules\lodash-es\lodash.js from vue-devui\node_modules\.pnpm\vitepress@0.20.1_sass@1.49.8\node_modules\vitepress\dist\client\app\temp\app.js not supported.
Instead change the require of lodash.js in vue-devui\node_modules\.pnpm\vitepress@0.20.1_sass@1.49.8\node_modules\vitepress\dist\client\app\temp\app.js to a dynamic import() which is available in all CommonJS modules.
```

fix: fix build error caused by lodash-es

---

packages/devui-vue/devui/progress/index.ts

Update:
1. `import { Progress } from './src/progress'` -> `import Progress from './src/progress'`，解决`pnpm build`报错问题
```
vitepress v0.20.1
- building client + server bundles...
Error when using sourcemap for reporting an error: Can't resolve original location of error.
'Progress' is not exported by devui/progress/src/progress.tsx, imported by devui/progress/index.ts
file: /home/runner/work/vue-devui/vue-devui/packages/devui-vue/devui/progress/index.ts:1:9
1: import { Progress } from "./src/progress";
^
2: Progress.install = function(app) {
3:   app.component(Progress.name, Progress);
✖ building client + server bundles...
build error:
Error: 'Progress' is not exported by devui/progress/src/progress.tsx, imported by devui/progress/index.ts
```

fix(progress): fix progress import error

---

packages/devui-vue/devui/table/src/column/use-column.ts
packages/devui-vue/devui/table/src/fix-header.tsx
packages/devui-vue/devui/table/src/normal-header.tsx
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

fix(table): 修复列排序bug；d-column增加默认插槽；抽离部分逻辑，降低圈复杂度

fix(Table): 修复列排序bug；d-column增加默认插槽；抽离部分逻辑，降低圈复杂度

---

packages/devui-vue/devui/tooltip/index.ts
packages/devui-vue/devui/tooltip/src/tooltip-types.ts
packages/devui-vue/devui/tooltip/src/tooltip.scss
packages/devui-vue/devui/tooltip/src/tooltip.tsx
packages/devui-vue/devui/tooltip/src/use-tooltip.ts
packages/devui-vue/docs/components/tooltip/index.md

refactor(Tooltip): 重构Tooltip

---

packages/devui-vue/devui/form/src/use-validate.ts

refactor(form): 提取校验函数到use-validate

---

packages/devui-vue/devui/form/src/directive/d-validate.ts
packages/devui-vue/devui/form/src/directive/style.scss
packages/devui-vue/devui/form/src/form-types.ts
packages/devui-vue/devui/form/src/util/index.ts

refactor(form): 完成d-validate指令功能

---

packages/devui-vue/devui/tabs/src/tab.tsx
packages/devui-vue/devui/tabs/src/tabs.tsx
packages/devui-vue/docs/components/tabs/index.md

1. `d-tab`子组件自定义插槽命名由`dTabTitle`改为`title`。
2. API统一采用中划线格式命名。

refactor(Tabs): refactor Tabs

---

.husky/pre-commit
.ls-lint.yml
package.json
packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-alpha-slider.tsx
packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-hue-slider.tsx
packages/devui-vue/devui/color-picker/src/components/color-palette/color-palette.tsx
packages/devui-vue/devui/color-picker/src/utils/dom-dragger.ts

Updates:
1. 修复`ls-lint/eslint/stylelint`不生效的问题
2. 修复`ColorPicker`组件文件命名格式问题：`domDragger.ts`->`dom-dragger.ts`

fix: fix ls-lint/eslint/stylelint

---

packages/devui-vue/devui/cascader/components/cascader-tag/index.scss
packages/devui-vue/devui/comment/src/comment.scss
packages/devui-vue/devui/editable-select/src/editable-select.scss
packages/devui-vue/devui/form/src/directive/style.scss
packages/devui-vue/devui/form/src/form-item/form-item.scss
packages/devui-vue/devui/upload/src/upload.scss

style: fix stylelint errors

---

packages/devui-vue/devui/skeleton/__tests__/skeleton-item.spec.ts
packages/devui-vue/devui/skeleton/src/item/item.tsx
packages/devui-vue/devui/skeleton/src/skeleton.tsx

style(skeleton): 手动修复 Eslint 报错

---

packages/devui-vue/devui/radio/index.ts
packages/devui-vue/devui/radio/src/radio-group.tsx
packages/devui-vue/devui/radio/src/radio.scss
packages/devui-vue/devui/radio/src/radio.tsx

1. 修复 eslint 报错
2. 格式化代码统一代码风格

refactor(radio): 修复 eslint 报错、格式化代码统一代码风格

---

packages/devui-vue/docs/en-US/components/panel/index.md

修复了英文文档demo无法现实的错误
更新了英文文档Api命名错误

docs(panel): 修复了英文文档中的错误

---

packages/devui-vue/devui/radio/src/radio.scss
packages/devui-vue/devui/radio/src/radio.tsx
packages/devui-vue/devui/style/theme/_color.scss

fix(Radio): 修改Radio组件圆圈外层选中和禁用样式，个别动画参数用变量代替

fix(Radio): 修改Radio组件圆圈外层选中和禁用样式，个别动画参数用变量代替

---

packages/devui-vue/devui/tree/src/composables/use-draggable.ts
packages/devui-vue/devui/tree/src/composables/use-lazy.ts
packages/devui-vue/devui/tree/src/tree-types.ts

chore: Tree 组件eslint报错修复

---

packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/body/body.tsx
packages/devui-vue/devui/table/src/components/fix-header.tsx
packages/devui-vue/devui/table/src/components/header/header.scss
packages/devui-vue/devui/table/src/components/header/header.tsx
packages/devui-vue/devui/table/src/composable/use-table.ts
packages/devui-vue/devui/table/src/table.scss
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

feat(Table): 使用Rem规范修改Table组件样式命名

feat(Table): 使用Rem规范修改Table组件样式命名

---

packages/devui-vue/docs/components/tag/index.md
packages/devui-vue/docs/en-US/components/tag/index.md

包括以下改动：
1. 名称使用中划线规范
2. 修复英文文档中跳转demo的锚链接大写开头不跳转的bug

docs(tag): 补全中英文文档

---

packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/composable/use-table.ts
packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/devui/table/src/table.scss
packages/devui-vue/docs/components/table/index.md

feat(Table): 新增borderType参数，支持设置表格边框类型

feat(Table): 新增borderType参数，支持设置表格边框类型

---

packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree-data.ts
packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree.spec.tsx
packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree-data.ts
packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
packages/devui-vue/devui/tree/__tests__/node-merge/node-merge-data.ts
packages/devui-vue/devui/tree/__tests__/node-merge/node-merge.spec.tsx
packages/devui-vue/devui/tree/__tests__/tree.spec.ts
packages/devui-vue/devui/tree/src/composables/use-merge-node.ts

增加以下单元测试：
- 应该正确渲染展开/收起按钮
- 点击节点时，该节点应该高亮
- 设置`disabled`为`true`时，节点应该禁用，不可点击
- 所有子节点均只有一个子节点时，应该折叠父节点
- 设置`checkable`为`true`时，应该在节点前面正确渲染`checkbox`
- 点击`checkbox`应该能正确勾选或取消勾选`checkbox`

test(tree): 完善tree组件基本功能的单元测试

---

packages/devui-vue/devui/tree/src/components/icon-close.tsx
packages/devui-vue/devui/tree/src/components/icon-open.tsx
packages/devui-vue/devui/tree/src/components/tree-node-toggle.tsx
packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/devui/tree/src/core/tree-factory-types.ts
packages/devui-vue/devui/tree/src/core/tree-factory.ts
packages/devui-vue/devui/tree/src/core/use-check.ts
packages/devui-vue/devui/tree/src/core/use-core.ts
packages/devui-vue/devui/tree/src/core/use-disable.ts
packages/devui-vue/devui/tree/src/core/use-operate.ts
packages/devui-vue/devui/tree/src/core/use-select.ts
packages/devui-vue/devui/tree/src/core/use-toggle.ts
packages/devui-vue/devui/tree/src/core/use-tree.ts
packages/devui-vue/devui/tree/src/core/utils.ts

Updates:
- 使用`useTree`方案替代`TreeFactory`方案
- 增加以下`composables`:
- `useTree` 主入口
- `useCore` 核心功能
- `useSelect` 点击选择
- `useCheck` 勾选
- `useToggle` 展开/收起
- `useDisable` 禁用
- `useOperate` 增删改操作

refactor(tree): 增加useTree并支持插件机制

---

packages/devui-vue/devui/progress/src/progress-types.ts
packages/devui-vue/devui/progress/src/progress.tsx
packages/devui-vue/devui/rate/src/rate.tsx
packages/devui-vue/devui/splitter/__tests__/splitter.spec.ts
packages/devui-vue/devui/timeline/__tests__/timeline.spec.ts
packages/devui-vue/devui/timeline/src/timeline-types.ts
packages/devui-vue/devui/timeline/src/timeline.tsx

修复以下组件eslint问题：
1. Splitter
2. Timeline
3. Progress
4. Rate

chore: 修复部分组件eslint问题

---

packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/config.tsx
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 表格支持索引列

---

packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
packages/devui-vue/devui/auto-complete/index.ts
packages/devui-vue/devui/auto-complete/src/auto-complete-types.ts
packages/devui-vue/devui/auto-complete/src/auto-complete.scss
packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx
packages/devui-vue/devui/auto-complete/src/composables/use-custom-template.ts
packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
packages/devui-vue/devui/auto-complete/src/composables/use-keyboard-select.ts
packages/devui-vue/devui/auto-complete/src/composables/use-lazy-handle.ts
packages/devui-vue/devui/auto-complete/src/composables/use-searchfn.ts
packages/devui-vue/devui/auto-complete/src/composables/use-select-handle.ts
packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
packages/devui-vue/docs/components/auto-complete/index.md
packages/devui-vue/docs/en-US/components/auto-complete/api-en.md
packages/devui-vue/tsconfig.json

fix(auto-complete): 修复eslint和单元测试问题

---

packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/config.tsx
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 丰富自定义列参数&新增支持自定义表头

feat(Table): 丰富自定义列参数&新增支持自定义表头

---

packages/devui-vue/docs/.vitepress/devui-theme/styles/demo-block.scss
packages/devui-vue/docs/.vitepress/devui-theme/styles/layout.scss
packages/devui-vue/docs/components/button/index.md
packages/devui-vue/docs/components/fullscreen/index.md

优化以下组件的 demo 文档：
- Button
- Fullscreen

docs(button): optimize demo

---

packages/devui-vue/devui-cli/commands/create.js
packages/devui-vue/devui-cli/templates/component.js
packages/devui-vue/docs/components/cascader/index.md

根据[开发规范](https://vue-devui.gitee.io/contributing/)优化创建组件模板的 devui-cli 脚本。

refactor(devui-cli): 优化创建组件模板的脚本

---

packages/devui-vue/docs/components/popover/index.md

feat(Popover): 优化Popover组件文档

---

packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/column.tsx
packages/devui-vue/devui/table/src/components/filter/filter-types.ts
packages/devui-vue/devui/table/src/components/filter/filter.scss
packages/devui-vue/devui/table/src/components/filter/filter.tsx
packages/devui-vue/devui/table/src/components/filter/index.ts
packages/devui-vue/devui/table/src/components/filter/multiple-filter.tsx
packages/devui-vue/devui/table/src/components/filter/single-filter.tsx
packages/devui-vue/devui/table/src/components/filter/use-filter.ts
packages/devui-vue/devui/table/src/components/header-th/header-th.tsx
packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
packages/devui-vue/devui/table/src/components/header/header.scss
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/store/store-types.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): Table支持筛选功能

---

packages/devui-vue/devui/slider/__tests__/slider.spec.ts
packages/devui-vue/devui/slider/src/slider.tsx
packages/devui-vue/docs/components/slider/index.md

fix(Slider): 修复disabled时input未禁用 [#471](https://github.com/DevCloudFE/vue-devui/issues/471)

fix(Slider): 修复disabled时input未禁用

---

packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/devui/tree/src/components/use-tree-node.ts
packages/devui-vue/devui/tree/src/core/use-check.ts
packages/devui-vue/devui/tree/src/core/use-core.ts
packages/devui-vue/devui/tree/src/core/use-tree-types.ts
packages/devui-vue/docs/components/tree/index.md

父子节点勾选关联的逻辑：
- 勾选父节点应该同步勾选全部嵌套的子节点（取消勾选的逻辑同理）
- 勾选子节点应该同时更新父节点的勾选状态
- 如果全部子节点被勾选，则其父节点也应该勾选
- 如果全部子节点取消勾选，其父节点也应该取消勾选
- 如果子节点只有部分被勾选，则父节点应该半选

feat(tree): 勾选功能增加父子关联逻辑

---

packages/devui-vue/docs/components/slider/index.md
packages/devui-vue/docs/en-US/components/slider/index.md

补充color属性的相关文档  （[#472](https://github.com/DevCloudFE/vue-devui/issues/472)）

docs(slider): 补充color属性的相关文档

---

packages/devui-vue/devui/menu/index.ts
packages/devui-vue/devui/menu/src/composables/layer-composables.ts
packages/devui-vue/devui/menu/src/menu.scss
packages/devui-vue/docs/components/menu/index.md
packages/devui-vue/docs/en-US/components/menu/index.md

- 修复了组件动画速度过慢问题
- 修复了组件未使用主题变量问题
- 修复了菜单项在收缩时无动画问题
- 移除了遗留在代码中的debugger
- 下调了组件的开发进度
- 90% -> 60%
- 完善了文档

fix(menu): 修复了若干组件问题

---

packages/devui-vue/devui/progress/__tests__/progress.spec.ts
packages/devui-vue/devui/progress/src/progress-types.ts
packages/devui-vue/devui/progress/src/progress.scss
packages/devui-vue/devui/progress/src/progress.tsx
packages/devui-vue/docs/components/progress/index.md
packages/devui-vue/docs/en-US/components/progress/index.md

feat(Progress): add `percentageTextPlacement` `percentageTextColor` api

---

packages/devui-vue/devui/badge/src/badge-types.ts
packages/devui-vue/docs/components/badge/index.md

+ Badge组件增加了 status 的默认值为 danger。
+ 修改Badge组件文档api中status属性描述。

fix(Badge): Badge组件无status值不显示dot (#507)

---

packages/devui-vue/devui/button/src/button.scss

鼠标移入元素依然会触发 hover 设置颜色， disabled 设置了颜色就不会被覆盖。

fix(Button): Button组件形态为outline，类型为primary禁用的情况下，不应该有hover效果 (#575)。

---

packages/devui-vue/docs/components/grid/index.md

其他组件文档也有类似情况,原因都是把颜色值写死了. #563

docs(grid): 使用css变量解决Grid组件组件黑暗主题下背景颜色错误

---

packages/devui-vue/devui/tree/src/composables/use-core.ts

开发虚拟滚动的时候试着渲染了150条数据，发现性能损耗有点大，Tree组件耗时 1000+ms，排查了一下，没有子节点不就不尝试获取子节点能大大提升性能。

fix(tree): 如果是叶子结点，不需要尝试获取子节点，以提升性能

---

packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
packages/devui-vue/devui/menu/src/components/sub-menu/use-sub-menu.ts
packages/devui-vue/devui/menu/src/menu.tsx
packages/devui-vue/devui/menu/src/styles/clear.scss
packages/devui-vue/devui/menu/src/styles/horizontal.scss
packages/devui-vue/devui/menu/src/styles/vertical.scss
packages/devui-vue/docs/components/menu/index.md
packages/devui-vue/docs/en-US/components/menu/index.md

- 修改范围： menu
- 修改内容如下
- 增加文档
- 仅展开一项（中/英）
- 重构类名
- `position: fixed` -> `position: absolute`
- 修复了横向排列，尺寸过小时出现省略号，二级菜单无法显示问题

refactor(menu): 重构类名

---

.eslintignore
CONTRIBUTING.md
packages/devui-vue/devui-cli/commands/code-check.js

update:
1. 在贡献者指南中补充代码检查脚本命令的文档
2. 修复单元测试脚本命令执行失效的问题
3. 移除`.eslintignore`中无效的代码

docs: 补充代码检查脚本命令的文档

---

packages/devui-vue/devui/search/__tests__/search.spec.ts
packages/devui-vue/devui/search/src/search.tsx

问题来源：https://github.com/DevCloudFE/vue-devui/issues/997
1. 修复点击clear按钮以及search按钮时，input输入框将会失焦的问题（使用label标签包裹）
2. 增加对该问题的测试except

fix(search): 修复点击search组件区域内按钮会使得组件失焦的问题

---

packages/devui-vue/devui/checkbox/src/checkbox-button.scss

checkbox-button 追光主题下样式异常，将颜色改为与边框一致的scss变量

fix(checkbox): checkbox-button 追光主题下样式异常 (close #1015);

---

packages/devui-vue/devui/cascader/components/cascader-item/index.tsx

原写法`cascaderItem?.children?.length`会在`length=0`时，渲染`0`，并不会自动转为`false`。

fix(Cascader): 修复条件判断不严谨导致DOM渲染错误

---

package.json
packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/src/components/body/body-types.ts
packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/body/body.tsx
packages/devui-vue/devui/table/src/components/body/use-body.ts
packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md
pnpm-lock.yaml

https://github.com/DevCloudFE/vue-devui/issues/1058
Table懒加载功能添加
使用WebAPI：IntersectionObserver 实现，不支持IE

feat(table): Table组件添加懒加载功能 #1058

---

packages/devui-vue/devui/back-top/src/back-top.tsx
packages/devui-vue/devui/textarea/src/composables/use-textarea-event.ts
packages/devui-vue/devui/textarea/src/textarea.tsx
packages/devui-vue/docs/components/back-top/index.md
packages/devui-vue/docs/components/textarea/index.md

- back-top 组件中的 click 就是原生容器的 click 事件，无必要添加
- textarea 组件中的 update 事件与 update:modelValue 事件重复，无必要添加

refactor: 移除back-top和textarea组件中的无用api

---

packages/devui-vue/devui/panel/__tests__/panel.spec.ts
packages/devui-vue/package.json
pnpm-lock.yaml

- 更新pnpm-lock文件以解决安装依赖失败的问题
- 更新vue版本为3.2.31以解决date-picker-pro单测失败问题
- 修改panel单元测试

fix: 解决写死registry导致的依赖安装失败

---

.github/workflows/preview-build.yml
.github/workflows/preview-deploy.yml

给PR/review 增加更好的体验，本次pr的ci会给每次的pr生成预览站点。
预览域名为：https://vue-devui-pr-${{ prId }}.surge.sh
如下图
> ref: https://surge.sh/
```bash
npx surge token
```
输入邮箱跟密码即可生成token，token填入GitHub仓库的token里面，如下图。token的key为`SURGE_TOKEN`,value为上面生成的token。

chore: add pull request preview github action

---

packages/devui-theme/src/theme/theme-data.ts
packages/devui-vue/devui/carousel/__tests__/carousel.spec.ts
packages/devui-vue/devui/carousel/src/carousel.scss
packages/devui-vue/devui/carousel/src/carousel.tsx
packages/devui-vue/devui/carousel/src/types.ts
packages/devui-vue/docs/components/carousel/index.md

1、解决指示器无限主题颜色错误问题
2、解决`autoplay`为`false`时，仍自动轮播的问题
3、代码格式化调整，`render`函数移到`setup`中
4、`activeIndexChange`事件应该用`emit`触发，而不是通过`props`设置
5、文档格式化调整，参数和事件采用中划线风格

fix(Carousel): 解决指示器样式和自动轮播问题

---

packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx

修复 DatePickerPro 测试用例因日期格式不同导致的测试用例执行失
败

fix(DatePickerPro): 修复 DatePickerPro 测试用例因日期格式不同导致的测试用例执行失败

---

packages/devui-vue/devui/date-picker-pro/__tests__/const.ts
packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/utils.ts

解决以下单元测试报错：
```
Summary of all failing tests
FAIL devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
● date-picker-pro test › date-picker-pro select date
expect(received).toBe(expected) // Object.is equality
Expected: "2022/8/2"
Received: "2022/8/9"
83 |     const Items = monthContentContainer.findAll('td');
84 |     await Items[selectIndex].trigger('click');
> 85 |     expect(dayjs(datePickerProValue.value).format('YYYY/M/D')).toBe(
|                                                                ^
86 |       `${date.getFullYear()}/${date.getMonth() + 1}/${todayIndex > 20 ? date.getDate() - 1 : date.getDate() + 1}`
87 |     );
88 |
at Object.<anonymous> (devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx:85:64)
● date-picker-pro test › date-picker-pro v-model test …
```

fix(date-picker-pro): 解决DatePickerPro组件的单元测试报错

---

packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/docs/components/tree/index.md

1. 组件拖拽功能应该使用`draggable: true`, 而不是`dragdrop: true`
2. 增加 `onDragend` 事件, 在结束之后清除拖拽，以解决不同组件拖拽会焦距的问题。（`onDrop`在拖拽到有效目标且释放之后会触发、`onDragend`会在拖拽结束之后执行）

fix(tree): 修复名称修改带来的错误

---

packages/devui-vue/docs/.vitepress/config/head.ts

chore: fix vitepress head type

---

packages/devui-theme/src/styles-var/private/_z-index.scss
packages/devui-vue/devui/color-picker/src/color-picker.scss
packages/devui-vue/devui/loading/src/loading.scss
packages/devui-vue/devui/styles-var/private/_z-index.scss
packages/devui-vue/devui/table/src/table.scss
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

为table组件内容新增一层父级`devui-table-container`，与loading同级，在`devui-table-container`中进行scroll操作，这样loading在外层不会随着滚动而滚动。
loadingMask没有设置z-index，导致在组件中存在无法覆盖全的问题，如固定列时，固定的列设置了 z-index: 5，会浮在loadingMask之上：
by the way，将项目中部分不规范的 `z-index: 9999` 修改，增加内容层最高层级zIndex - `$devui-z-index-function-widget` 使其不至于超过临时层导致其他问题

fix(Table): #1083 修复table中loadingMask无法全覆盖table的问题

---

vue-devui.code-workspace

This PR improves developers experience(DX) by add a .code-workspace file to enable IDE monorepo enhancement.
Pain points:
- Hard to read our file structure because sub projects inside `packages/**` are too deep.

chore: add .code-workspace file

---

packages/devui-vue/devui/input-number/src/input-number-types.ts
packages/devui-vue/devui/input-number/src/input-number.tsx
packages/devui-vue/devui/input-number/src/use-input-number.ts

1. input 的输入框类型不应该为 number, number类型输入非数字不会触发更新事件导致输入框内容显示异常。
2. 修复 inputVal ts 类型错误
3. 输入不合规的字符，显示最后一次正确值。
4. 其他一些优化

fix(input-number): 修复ts类型错误，输入框输入非数字显示异常等问题

---

packages/devui-vue/devui/menu/__tests__/menu.spec.ts
packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
packages/devui-vue/devui/menu/src/composables/use-nearest-menu-element.ts
packages/devui-vue/devui/menu/src/menu.scss
packages/devui-vue/devui/menu/src/menu.tsx
packages/devui-vue/devui/menu/src/styles/clear.scss
packages/devui-vue/devui/menu/src/styles/horizontal.scss
packages/devui-vue/devui/menu/src/styles/public.scss
packages/devui-vue/devui/menu/src/styles/vertical.scss
packages/devui-vue/docs/components/menu/index.md
packages/devui-vue/docs/en-US/components/menu/index.md

- 逻辑修复
- 修复溢出菜单中，router无法点击
- 修复溢出再显示后无法点击的bug
- 修复溢出菜单再显示，最后一个元素闪烁问题
- 单元测试
- 增加单元测试
- 样式修复
- 修复如果鼠标悬浮在任何一个menu-element上，同级的其他menu-element也会有hover的样式。
- 文档
- 添加 仅展开一项
- 修复 key错误

fix(menu): 修复部分样式错误

---

packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
packages/devui-vue/devui/input-number/src/input-number-types.ts
packages/devui-vue/devui/input-number/src/use-input-number.ts
packages/devui-vue/docs/components/input-number/index.md

1.  增加正则限制功能
2. 增加正则限制文档
3. 增加正则限制测试

feat(input-number): 增加正则限制

---

packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
packages/devui-vue/devui/cascader/src/cascader.scss
packages/devui-vue/devui/cascader/src/cascader.tsx
packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
packages/devui-vue/devui/drawer/src/drawer-types.ts
packages/devui-vue/devui/drawer/src/drawer.tsx
packages/devui-vue/devui/dropdown/src/use-dropdown.ts
packages/devui-vue/devui/editable-select/src/editable-select.tsx
packages/devui-vue/devui/image-preview/src/image-preview.scss
packages/devui-vue/devui/modal/src/modal-types.ts
packages/devui-vue/devui/modal/src/modal.scss
packages/devui-vue/devui/modal/src/modal.tsx
packages/devui-vue/devui/notification/src/notification.scss
packages/devui-vue/devui/popover/src/use-popover.ts
packages/devui-vue/devui/select/src/select.tsx
packages/devui-vue/devui/time-picker/src/time-picker.tsx
packages/devui-vue/docs/components/modal/index.md

1、参考`z-index.scss`文件的规范，更新弹出类组件的层级，防止组合使用时互相遮挡
2、移除`Modal`组件的`width`参数，可在组件上通过`style/class`设置宽度
3、移除`Modal`组件的`top`参数，规范中不涉及距离顶部偏移量

fix: 更新弹出类组件的层级，避免被遮挡

---

packages/devui-vue/devui/table/src/components/column/config.tsx
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/store/store-types.ts
packages/devui-vue/devui/table/src/table.tsx

refactor(Table): 重构多选事件触发逻辑

---

packages/devui-vue/devui/editable-select/src/editable-select.tsx

fix(editable-select): fix #1253

---

packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts

test(editable-select): 增加对allow-clear属性的测试

---

packages/devui-vue/devui/checkbox/src/checkbox-group.scss
packages/devui-vue/devui/form/src/components/form-control/form-control.scss
packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
packages/devui-vue/devui/radio/src/radio-group.scss
packages/devui-vue/docs/components/form/index.md
packages/devui-vue/package.json
pnpm-lock.yaml

Form组件的popover提示检验信息的方式在表单控件外加了一层div元素并且设置了宽度是100%，导致表单控件宽度没有占满100%时，popover的提示距离表单控件较远。且Radio和CheckBox组件默认就是块级元素，也会导致popover提示距离表单控件较远

fix(Form): 修复校验提示距离表单控件较远的问题

---

packages/devui-vue/docs/components/form/index.md

修复 form 文档示例中 d-textarea 输入字符失去焦点清空数据的bug
v-model貌似不应该那么写🧐

fix(docs): 修复 form 文档示例中 d-textarea 输入字符失去焦点清空的bug (close #1287)

---

packages/devui-vue/devui/time-select/src/use-time-select.ts

修复 #1290 中提到的step小于等于0时会卡死的问题。
具体的解决思路为判断step是否严格大于00:00，目前默认只要大于等于00:00即为合法的step

fix(time-select): 修复 #1290 中step小于等于0时会卡死的问题

---

packages/devui-vue/devui/mention/src/mention.tsx
packages/devui-vue/devui/modal/src/modal.scss
packages/devui-vue/devui/select/src/use-select.ts
packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.scss
packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx

1. [fix(modal): 修复dialog的个第一个icon和其他的不对齐](https://github.com/DevCloudFE/vue-devui/pull/1301/commits/e285f720878a1217fa2c1a7e6a1e713d196f1ba2)https://github.com/DevCloudFE/vue-devui/issues/1300
使用flex布局修复icon不对齐问题
2. [修复select新增选项，删除一个，其他新增的选项全部被删除了](https://github.com/DevCloudFE/vue-devui/pull/1301/commits/5390d0bca6a0fdb1ebde2420c261b8d747f48f19) https://github.com/DevCloudFE/vue-devui/issues/1274
3. [fix(tabs): 修复Tabs溢出不截断](https://github.com/DevCloudFE/vue-devui/pull/1301/commits/219d0e15d179776228c65a37fc6e93222ddbbd1b) https://github.com/DevCloudFE/vue-devui/issues/1062
使多个tabs溢出可以滑动
4. [fix(mention): 修复Mention 组件的联想文字选中后应替换触发输入的联想文本，而非追加](https://github.com/DevCloudFE/vue-devui/pull/1301/commits/f3ef2b64008ea8435b0e8d6fe22d3d5403385fc6) …

fix: 修复 #1300 #1274 #1062 #1303

---

packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/HomeFooter.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/NavLinks.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/PageToc.vue
packages/devui-vue/docs/.vitepress/devui-theme/composables/sideBar.js
packages/devui-vue/docs/.vitepress/devui-theme/const.ts

fix: fix doc 404 close #1310

---

.github/workflows/pull-request.yml
.ls-lint.yml
package.json
packages/devui-vue/devui-cli/commands/code-check.js
scripts.json

- 通过 code-check 脚本解决单元测试报错，但PR门禁没有拦截住的问题

chore: refactor unit-test scripts

---

packages/devui-vue/devui/radio/src/radio-button.scss
packages/devui-vue/devui/radio/src/radio-types.ts
packages/devui-vue/devui/radio/src/radio.scss
packages/devui-vue/docs/components/radio/index.md

1. radio、radio-button组件 size 大小使用scss变量向标准统一
2. 去除 radio 组件 xs 类型
3.  文档修改

radio组件 size 大小使用scss变量向标准统一 #1199

---

packages/devui-vue/devui/checkbox/src/checkbox-button.scss
packages/devui-vue/devui/checkbox/src/checkbox-group.scss
packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
packages/devui-vue/devui/checkbox/src/checkbox-types.ts
packages/devui-vue/devui/checkbox/src/checkbox.scss
packages/devui-vue/docs/components/checkbox/index.md

1. checkbox 组件 size 大小使用scss变量向标准统一 #1199
2. checkbox-group 组件 direction 排列方向样式优化
3. checkbox组件文档更新 去除组件 size xs 类型及相关组件示例，按钮形态示例优化

checkbox 组件 size 大小使用scss变量向标准统一 #1199

---

packages/devui-vue/devui/dragdrop/src/const.ts
packages/devui-vue/devui/dragdrop/src/constant.ts
packages/devui-vue/devui/dragdrop/src/draggable-directive.ts
packages/devui-vue/devui/dragdrop/src/droppable-directive.ts
packages/devui-vue/devui/dragdrop/src/sortable-directive.ts
packages/devui-vue/devui/dragdrop/src/utils.ts

Optimize the code according to the review opinion #1144

refactor(dragdrop): Optimize the code according to the review opinion

---

packages/devui-vue/devui/color-picker/src/color-picker.tsx
packages/devui-vue/devui/color-picker/src/utils/composeable.ts

fix(colorPicker): 组件无法正常打开选择器

---

packages/devui-vue/devui/checkbox/src/checkbox.scss
packages/devui-vue/devui/checkbox/src/checkbox.tsx
packages/devui-vue/devui/transfer/__tests__/transfer.spec.ts

在部分浏览器的渲染下 checkbox icon 会向下偏移1px，就拿文档例子说，16px盒子大小，checkbox icon也为 16 * 16，向下偏移1px，且最外部容器在分组（group）下，会添加`overflow： hidden;` 样式 【`.devui-checkbox__wrap .devui-checkbox label`】，所以呈现的就是显示不全的情况。
> 兼容性Tips：目前在Windows下能够复现，Mac下Chrome无法复现（104.0），maybe 新版本修复了这个向下偏移的问题？
既然正常默认文档流的情况，checkbox - icon 在部分情况会向下偏移1px，那么我们让他不偏移即可。
这里我们将外部容器 label，修改为flex（原为block），并令子元素始终垂直居中 `align-items: center;` 即可。
- 其他带来问题修复：
- 原来的label文字是直接作为文字标签放到label中的，所以在label上设置的ellipsis是有效的，但label改为flex后，内部文字标签，会遵循弹性和模型子元素规则， 长度超过时会造成长度溢出。这里我们需要对文字标签进一步设置。
- 1. 将文字标签用span包裹起来（主要取个名字好设置css），设置css `flex-shrink: 1;` 令其会自动按照父级flex盒子大小缩减。
- 2. 同时要同步为 checkbox icon 标签设置样式 `flex-shrink: 0;` 让它不参与缩减，否则会被文字标签挤占宽度导致坍缩。
1. checkbox分组：
2. 其他checkbox情况（未受影响）：

fix(checkbox): #1323 修复checkboxGroup下，组件底部遮挡问题

---

packages/devui-vue/devui/checkbox/src/checkbox-button.scss
packages/devui-vue/devui/radio/src/radio-button.scss

fix(radio/checkbox): 修复 radio/checkbox group 按钮形态属性 direction="column" 时样式异常

---

packages/devui-vue/devui/cascader/src/cascader.scss

因close按钮也触发了rotate导致聚焦时按钮倾斜，移除close的rotate后样式正常

fix(cascader): 修复聚焦cascader按钮倾斜

---

packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/utils.ts

+ 修复 range-date-picker-pro v-model 测试用例错误，设置日期时大于20设置为当前日期，所以utils相关函数不应该大于20时-1
这个 getDateIndex 函数为什么要这么计算呢？哪位大佬明白的告知下

fix(date-picker-pro): 修复 range-date-picker-pro v-model 测试用例错误

---

packages/devui-vue/docs/en-US/components/button/index.md

前端小白想学习加入这个项目，但水平有限，先帮忙完善个文档叭~

docs(button): 新增button英文文档

---

packages/devui-vue/devui/tag-input/__tests__/tag-input.spec.ts
packages/devui-vue/devui/tag-input/src/tag-input-types.ts
packages/devui-vue/devui/tag-input/src/tag-input.scss
packages/devui-vue/devui/tag-input/src/tag-input.tsx
packages/devui-vue/docs/components/tag-input/index.md

+ 组件 class 使用 namespace，同步修改 测试用例
+ 修复 tag-input.tsx ts错误
+ 组件props noData 属性应该有默认值 否则待选择列表无数据样式会异常
+ 修正文档 props placeholder、noData 的数据类型，移除showAnimation 属性-移除的原因是 组件并没有定义这个属性

优化 tag-input 组件代码

---

packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/menu/__tests__/menu.spec.ts
packages/devui-vue/devui/message/__tests__/message.spec.tsx
packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts

1. test: 添加message测试用例
2. fix: 修复date-picker-pro单元测试用例报错
3. fix(menu): 修复menu单元测试用例报错

test: 添加message测试用例

---

packages/devui-vue/devui/mention/src/mention.tsx

fix(mention): 修复Mention组件设置position为top，输入第一个字符列表选项没有贴近输入框的问题 close #1439

---

packages/devui-vue/devui/radio/__tests__/radio-group.spec.ts
packages/devui-vue/devui/radio/__tests__/radio.spec.ts
packages/devui-vue/devui/radio/src/radio-types.ts
packages/devui-vue/devui/radio/src/radio.tsx
packages/devui-vue/devui/radio/src/use-radio.ts

1. 组件的 size > 表单的 size > 默认大小 md
2. 测试中组件设置了 size 属性，元素应该包含相关 class 类名

修复 Radio 组件 size 属性的逻辑 （#1199）

---

packages/devui-vue/devui/checkbox/__tests__/checkbox-button.spec.ts
packages/devui-vue/devui/checkbox/__tests__/checkbox-group.spec.ts
packages/devui-vue/devui/checkbox/__tests__/checkbox.spec.ts
packages/devui-vue/devui/checkbox/src/checkbox-types.ts
packages/devui-vue/devui/checkbox/src/checkbox.tsx
packages/devui-vue/devui/checkbox/src/use-checkbox.ts

1. 组件的 size > 表单的 size > 默认大小 md
2. 更改后的测试错误， 测试用例增加 wrapper.unmount()

修复 checkbox 组件 size 属性的逻辑 （#1199）

---

packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
packages/devui-vue/devui/time-picker/src/time-picker-types.ts

1. timePicker组件 props size 在表单内部时应该跟随表单变化
2. 增加 props size 优先级测试用例

timePicker组件 props size 在表单内部时应该跟随表单变化

---

packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
packages/devui-vue/devui/time-select/src/time-select-types.ts

timeSelect 组件 props size 在表单内部时应该跟随表单变化

timeSelect 组件 props size 在表单内部时应该跟随表单变化

---

packages/devui-vue/devui/modal/src/modal.tsx

fix(modal): 修复弹窗组件信息提示图标的颜色

---

packages/devui-vue/devui/image-preview/src/transform.ts

https://vue-devui.github.io/components/image-preview/
问题：
图片预览时，拖动图片后通过ZoomBest/ZoomOriginal重置图片后，再次拖动，图片会回到重置前的位置。

fix(ImagePreview): 修复图片拖动并重置，再次拖动时的位置问题

---

packages/devui-vue/docs/.vitepress/config/lang.ts

lang.ts文件中缺失复制成文本字段，代码里先使用配置文件中的文本导致Demo.vue配置的缺省值没有作用

feat: 1524 组件demo中，点击复制代码片段之后，文字消失问题解决

---

packages/devui-vue/docs/.vitepress/config/nav.ts

The display effect is as follows:

chore(site): add current version number to the top nav bar

---

packages/devui-vue/docs/components/layout/index.md

1. 修复 layout 文档示例未正确展示 logo 的bug。
2. 格式化代码风格。

docs(layout): 修复 layout 文档示例未正确展示 logo 的bug(#112)。

---

packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
packages/devui-vue/devui/image-preview/src/image-preview-service.ts
packages/devui-vue/tsconfig.json

1. 描述： iamge-preview 组件单行太长导致eslint没过构建失败，并修复了ts报红

fix: 修改eslint单行太长问题,对ts类型报红完善

---

packages/devui-vue/devui/menu/__tests__/menu.spec.ts
packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
packages/devui-vue/devui/menu/src/menu.tsx

1. 添加`menu`组件`router`属性测试用例；
2. `useRouter`使用响应式；
```javascript
const { openKeys, mode, collapsed, defaultSelectKeys } = toRefs(props);
provide('useRouter', props.router);
👇
const { openKeys, mode, collapsed, defaultSelectKeys, router } = toRefs(props);
provide('useRouter', router);
``` 
3. `prettier`代码风格格式化。

feat(Menu): add `menu` component `router` test case

---

packages/devui-vue/devui/tree/src/composables/use-operate.ts

issue #1581 
节点懒加载 [use-lazy-load](https://github.com/DevCloudFE/vue-devui/blob/dev/packages/devui-vue/devui/tree/src/composables/use-lazy-load.ts#L39 ) 通过 isLeaf 和 childNodeCount 来判断，在新增节点时，没有设置新增节点的 childNodeCount 属性，导致折叠父节点 [use-toggle](https://github.com/DevCloudFE/vue-devui/blob/dev/packages/devui-vue/devui/tree/src/composables/use-toggle.ts#L36) 时触发节点懒加载操作。
通过设置新增节点的 childNodeCount 属性，可以防止折叠节点时进入节点懒加载的逻辑。

fix(tree): tree组件新增节点时折叠父节点，父节点会变成懒加载状态

---

packages/devui-vue/docs/.vitepress/devui-theme/components/AlgoliaSearchBox.vue

解决使用搜索时地址栏出现//#xxx后，页面再次刷新会白屏的问题。

fix: 使用搜索后有//#刷新页面页面空白的问题 #1619

---

packages/devui-vue/devui/select/src/select.tsx

fix(select): 下拉没有内容的时候没有去除掉dom ul。 #1844

fix(select): 下拉没有内容的时候没有去除掉dom ul。 修复 #1844

---

packages/devui-vue/devui/breadcrumb/src/utils.ts
packages/devui-vue/devui/category-search/src/components/text-input-menu.tsx
packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
packages/devui-vue/devui/input-number/index.ts
packages/devui-vue/devui/input-number/src/input-number-types.ts
packages/devui-vue/devui/input-number/src/use-input-number.ts
packages/devui-vue/docs/components/input-number/index.md

支持inputNumber可以允许输入空串值，即用户删除掉所有值之后有效 对应issues #1843

fix:  解决InputNumber数字输入框，去除掉值之后失焦/确认之后会变成数值0的问题。

---

packages/devui-vue/devui/shared/utils/dom.ts

fix:兼容火狐浏览器无法正确判断元素（DevCloudFE#1883）

---

packages/devui-vue/devui/code-review/src/code-review.scss
packages/devui-vue/devui/code-review/src/code-review.tsx
packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
packages/devui-vue/devui/code-review/src/utils.ts
packages/devui-vue/package.json

* fix(code-review): 双栏模式下支持半边选中文本

fix(code-review): 双栏模式下支持半边选中文本 (#1931)
