README.md
packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
packages/devui-vue/docs/components/accordion/index.md
yarn.lock

Update:
1. fix accordion md dead link error

fix: fix accordion md dead link error

---

packages/devui-vue/devui/editable-select/src/composable/use-keyboard-select.ts

rename use-keyBoard-select into use-keyboard-select

fix(editable-select): rename keyBoard to keyboard

---

packages/devui-vue/devui/overlay/src/flexible-overlay.tsx

fix: flexibleOverlay修复backdropClick错误

---

packages/devui-vue/devui/style/theme/_color.scss

fix(button): 修复success按钮hover状态颜色错误的问题

---

packages/devui-vue/devui/accordion/src/accordion.scss

fix: del global style pollution in accordion

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml

chore: update ISSUE_TEMPLATE config

---

packages/devui-vue/devui/form/src/form-item/form-item.tsx

【Form】fix: 修复重置数组类型的值不正确问题

---

packages/devui-vue/devui/drawer/src/drawer-service.ts
packages/devui-vue/docs/components/button/index.md

Update:
1. Remove duplicate attribute: `class="mr-xs"`

fix(docs): fix button demo

---

packages/devui-vue/devui/tree/__tests__/tree.spec.ts
packages/devui-vue/devui/tree/src/tree.tsx

tree组件单元测试问题，tree组件folder部分嵌套div便于控制

fix: tree组件单元测试，tree组件folder部分嵌套div便于控制

---

packages/devui-vue/docs/components/form/index.md

docs(Form): 更新文档及demo示例

---

packages/devui-vue/docs/en-US/components/form/index.md

doc(Form): 增加英文文档

---

package.json
packages/devui-cli/package.json

fix(devui-cli): dc -> devui

---

packages/devui-vue/docs/vite.config.ts

修复了运行```yarn dev```命令时，vitepress初加载时的白屏问题

fix(docs): 修复了调试时首页白屏

---

packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/BackToTop.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/SideBarLink.js
packages/devui-vue/docs/.vitepress/devui-theme/styles/sidebar-links.scss

Update:
1. 移除__VP_STATIC_START__
2. 解决左侧组件导航换行问题
3. 解决回到顶部不显示的问题

fix: 解决几个网站问题

---

packages/devui-vue/devui/button/index.ts
packages/devui-vue/devui/button/src/button-types.ts
packages/devui-vue/devui/button/src/button.scss
packages/devui-vue/devui/button/src/button.tsx
packages/devui-vue/devui/button/src/use-button.ts
packages/devui-vue/devui/style/theme/_color.scss
packages/devui-vue/docs/components/button/index.md
packages/devui-vue/docs/components/carousel/index.md
packages/devui-vue/docs/components/form/index.md
packages/devui-vue/docs/components/loading/index.md
packages/devui-vue/docs/components/modal/index.md
packages/devui-vue/docs/components/pagination/index.md
packages/devui-vue/docs/components/popover/index.md
packages/devui-vue/docs/components/table/index.md
packages/devui-vue/docs/components/toast/index.md
packages/devui-vue/docs/components/tooltip/index.md
packages/devui-vue/docs/components/upload/index.md

优化Button组件API，抽离逻辑，更新其他组件demo中Button的用法

fix(Button): 优化Button组件API，抽离逻辑，更新其他组件demo中Button的用法

---

packages/devui-vue/devui/fullscreen/src/composables/use-fullscreen.ts
packages/devui-vue/devui/fullscreen/src/composables/use-keydown.ts
packages/devui-vue/devui/fullscreen/src/fullscreen-types.ts
packages/devui-vue/devui/fullscreen/src/fullscreen.scss
packages/devui-vue/devui/fullscreen/src/fullscreen.tsx
packages/devui-vue/devui/fullscreen/src/utils.ts
packages/devui-vue/docs/components/fullscreen/index.md

Update:
1. 按照以下方案进行`Fullscreen`组件的优化：[https://github.com/DevCloudFE/vue-devui/discussions/76](https://github.com/DevCloudFE/vue-devui/discussions/76)

refactor(fullscreen): optimize fullscreen api and demo

---

packages/devui-vue/devui/select/src/select.scss

style(Select): 补充样式，此样式在网站全局样式中存在，所以网站上看demo效果正常；脱离网站使用组件时，会出现样式问题

refactor(Select): 补充样式

---

packages/devui-vue/devui/list/index.ts
packages/devui-vue/devui/list/src/list-item.scss
packages/devui-vue/devui/list/src/list-item.tsx
packages/devui-vue/devui/list/src/list.scss
packages/devui-vue/devui/list/src/list.tsx
packages/devui-vue/docs/components/list/index.md

refactor(list): 封装List组件基础样式

---

packages/devui-vue/devui/form/src/directive/d-validate-rules.ts
packages/devui-vue/devui/form/src/directive/style.scss
packages/devui-vue/devui/form/src/form-control/form-control.scss
packages/devui-vue/devui/form/src/form-control/form-control.tsx
packages/devui-vue/devui/form/src/form-item/form-item.scss
packages/devui-vue/devui/form/src/form-item/form-item.tsx
packages/devui-vue/devui/form/src/form-label/form-label.scss
packages/devui-vue/devui/form/src/form-label/form-label.tsx
packages/devui-vue/devui/form/src/form-operation/form-operation.scss
packages/devui-vue/devui/form/src/form-operation/form-operation.tsx
packages/devui-vue/devui/form/src/form.scss
packages/devui-vue/devui/form/src/form.tsx
packages/devui-vue/devui/style/core/_form.scss

refactor(form): 给样式名增加devui-前缀

---

packages/devui-vue/devui/badge/src/badge-types.ts
packages/devui-vue/devui/badge/src/badge.scss
packages/devui-vue/docs/components/badge/index.md

feat: Badge组件增加common类型

---

packages/devui-theme/src/theme-collection/extend-theme-vue.scss
packages/devui-vue/devui/button/src/button.tsx
packages/devui-vue/docs/.vitepress/devui-theme/styles/index.scss

feat: 修改Tab和Button无限主题的颜色

---

packages/devui-vue/package.json
pnpm-lock.yaml

在执行 `build:lib` 的时候会收集最近的 commit 记录生产 `changelog.md` 文件

chore: 生成 changelog.md

---

packages/devui-vue/devui/icon/__tests__/icon.spec.ts
packages/devui-vue/devui/icon/index.ts
packages/devui-vue/devui/icon/src/icon-types.ts
packages/devui-vue/devui/icon/src/icon.tsx

Updates:
1. 修复Icon组件ESLint问题
2. 抽取类型文件`icon-types.ts`保持代码风格的统一

refactor(icon): 优化Icon组件，修复ESLint问题

---

packages/devui-vue/devui/input-number/src/input-number.scss

input-number组件size三种状态下（lg,normal,sm）大小优化。

fix: input-number组件size大小样式调整优化

---

packages/devui-vue/devui/select/hooks/use-cache-options.ts
packages/devui-vue/devui/select/index.ts
packages/devui-vue/devui/select/src/select.tsx
packages/devui-vue/devui/select/src/use-select.ts

@all-contributors please add @unfound  for code

fix(select): 修复eslint的错误和警告

---

packages/devui-vue/devui/shared/hooks/use-namespace.ts

feat: 新增useNamespace hooks，采用Bem规范统一样式命名

feat: 新增useNamespace hooks，采用Bem规范统一样式命名

---

packages/devui-vue/devui/select/src/select.scss
packages/devui-vue/devui/style/theme/_color.scss

fix(Select): 修改Select组件的输入框背景色

fix(Select): 修改Select组件的输入框背景色

---

packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/header/header.scss

fix(Table): 替换Table组件部分样式为样式变量

fix(Table): 替换Table组件部分样式为样式变量

---

.prettierrc
packages/devui-vue/devui/progress/src/progress.scss
packages/devui-vue/devui/progress/src/progress.tsx

fix(Badge): 替换Badge组件部分样式为样式变量

fix(Progress): 替换Progress组件部分样式为样式变量

---

packages/devui-vue/docs/.vitepress/config/nav.ts

docs(nav): update playground link

---

packages/devui-vue/devui/ripple/src/options.ts
packages/devui-vue/devui/ripple/src/utils/create-container-element.ts
packages/devui-vue/devui/ripple/src/utils/create-ripple-element.ts
packages/devui-vue/devui/ripple/src/utils/ripple-count.ts
packages/devui-vue/devui/ripple/src/v-ripple.ts
packages/devui-vue/docs/components/ripple/index.md
packages/devui-vue/docs/en-US/components/ripple/index.md

first commit
1. 修复 已知 Eslint
2. 优化中英文文档
3. delay-time Api 修改为 delay 并且 时间单位全部切换成 ’秒‘ 统一单位
second commit
1. 修复剩余所有ripple eslint 
2. 优化文档
3. 时间number 类型Api 统一规范成毫秒

fix(ripple): 修复ripple指令eslint 优化 api 优化中英文文档

---

packages/devui-vue/devui/tabs/src/tabs.scss

fix: 修复tabs最后一个圆角样式问题

---

packages/devui-vue/devui/overlay/src/flexible-overlay/use-flexible-overlay.ts

fix(Popover): 修复Popover动态渲染时的bug

fix(Popover): 修复Popover动态渲染时的bug

---

packages/devui-vue/devui/tree/src/composables/use-draggable.ts

fix(Tree): 修复Tree组件引入lodash不准确，导致业务vite构建报错问题

fix(Tree): 修复Tree组件引入lodash不准确，导致业务vite构建报错问题

---

packages/devui-vue/devui/table/src/components/body/body.tsx
packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/column.tsx
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
packages/devui-vue/devui/table/src/components/header/header.tsx
packages/devui-vue/devui/table/src/components/header/use-header.ts
packages/devui-vue/devui/table/src/components/normal-header.tsx
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/store/store-types.ts
packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/devui/table/src/table.scss
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

feat(Table): 新增Table组件表头分组功能

---

packages/devui-vue/docs/en-US/components/badge/index.md

docs: 添加badge的英文文档

---

packages/devui-vue/devui/badge/__tests__/badge.spec.ts

fix: 修复badge单元测试props属性错误问题

---

packages/devui-vue/devui/image-preview/__tests__/image-preview.spec.ts
packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
packages/devui-vue/devui/image-preview/src/image-preview-service.ts
packages/devui-vue/devui/image-preview/src/image-preview-types.ts
packages/devui-vue/devui/image-preview/src/image-preview.tsx
packages/devui-vue/devui/image-preview/src/transform.ts
packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts

- 修复image-preview的eslint问题、代码规范格式

chore(image-preview): 修复image-preview的eslint问题、代码规范格式

---

packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/devui/tree/src/components/use-tree-node.ts
packages/devui-vue/devui/tree/src/const.ts
packages/devui-vue/devui/tree/src/core/use-core.ts
packages/devui-vue/devui/tree/src/core/use-tree-types.ts
packages/devui-vue/devui/tree/src/tree.scss
packages/devui-vue/docs/components/tree/index.md

feat(tree): 增加节点连接线

---

packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 优化Table组件文档

---

packages/devui-vue/devui/tree/src/components/tree-node-content.tsx
packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/devui/tree/src/new-tree.tsx
packages/devui-vue/docs/components/tree/index.md

给`tree`组件增加以下插槽：
- icon：用于定制展开/收起图标
- content：用于定制节点内容

feat(tree): add tree content/icon slot

---

packages/devui-vue/devui/modal/__tests__/modal.spec.tsx

test(Modal): 补充Modal组件单元测试

---

packages/devui-vue/devui/table/src/components/header/header.scss
packages/devui-vue/docs/components/table/index.md

fix(Table): 优化Table组件文档和表头样式

---

packages/devui-vue/devui/notification/__tests__/notification.spec.tsx

test(Notification): 补充Notification单元测试

test(Notification): 补充Notification单元测试

---

packages/devui-vue/devui/table/__tests__/table.spec.ts
packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/index.ts

test(Table): 补充Table组件单元测试

---

packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/devui/tree/src/core/use-check.ts
packages/devui-vue/devui/tree/src/core/use-core.ts
packages/devui-vue/devui/tree/src/core/use-operate.ts
packages/devui-vue/devui/tree/src/core/use-select.ts
packages/devui-vue/devui/tree/src/core/use-tree-types.ts
packages/devui-vue/devui/tree/src/new-tree-types.ts
packages/devui-vue/devui/tree/src/new-tree.tsx
packages/devui-vue/docs/components/tree/index.md

Updates:
1. 给tree组件增加`check`用于配置勾选功能
2. 增加`toggleSelectNode`用于取消高亮
3. 增加tree组件api文档
4. 优化tree组件demo

docs(tree): 优化tree组件api/demo

---

packages/devui-vue/devui/notification/__tests__/notification.spec.tsx

fix(Notification): 修正Notification组件单元测试

fix(Notification): 修正Notification组件单元测试

---

packages/devui-vue/devui/rate/src/rate-types.ts
packages/devui-vue/devui/rate/src/rate.tsx
packages/devui-vue/docs/components/rate/index.md

fix(Rate): 修复 rate 组件半选模式报错 (#376)

---

packages/devui-vue/devui/textarea/src/textarea-types.ts
packages/devui-vue/docs/components/textarea/index.md

feat(Textarea): 优化Textarea文档格式

feat(Textarea): 优化Textarea文档格式

---

CONTRIBUTING.md

fix: GitHub format

---

.all-contributorsrc
README.md

Reverts DevCloudFE/vue-devui#439

Revert "docs: add Bob as a contributor for code"

---

packages/devui-vue/devui/dropdown/src/dropdown-types.ts
packages/devui-vue/devui/dropdown/src/dropdown.tsx
packages/devui-vue/devui/overlay/src/flexible-overlay/flexible-overlay-types.ts
packages/devui-vue/devui/overlay/src/flexible-overlay/use-flexible-overlay.ts
packages/devui-vue/docs/components/dropdown/index.md
packages/devui-vue/package.json
pnpm-lock.yaml

fix(Dropdown): 修复Dropdown隐藏不销毁时位置不更新的bug&支持贴视图边界对齐时设置偏移量

fix(Dropdown): 修复Dropdown隐藏不销毁时位置不更新的bug&支持贴视图边界对齐时设置偏移量

---

packages/devui-vue/docs/components/rate/index.md

修正 rate 组件文档 中文名称、移除多余文字、参数命名 allowHalf 改为 allow-half

docs(rate): 修正 rate组件文档 中文名称、移除多余文字、参数命名 allowHalf 改为 allow-half

---

packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts

fix(AutoComplete): 修复AutoComplete没有获取焦点时输入框高亮的bug

fix(AutoComplete): 修复AutoComplete没有获取焦点时输入框高亮的bug

---

packages/devui-vue/devui/popover/src/popover.scss

fix(Popover): 修复Popover被Overlay覆盖样式的问题

fix(Popover): 修复Popover被Overlay覆盖样式的问题

---

packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.ts
packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx
packages/devui-vue/devui/dropdown/src/use-dropdown.ts

test(Dropdown): 补充Dropdown单元测试

test(Dropdown): 补充Dropdown单元测试

---

packages/devui-vue/devui/dropdown/src/dropdown.tsx

fix(Dropdown): 修复Dropdown漏传参数问题

fix(Dropdown): 修复Dropdown漏传参数问题

---

packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts

docs(Select): 添加select的主页地址和头像

---

packages/devui-vue/devui/button/src/button.tsx

fix(Button): Button组件的图标大小需要用样式变量设置

fix(Button): Button组件的图标大小需要用样式变量设置

---

packages/devui-vue/devui/multi-auto-complete/__tests__/multi-auto-complete.spec.tsx
packages/devui-vue/devui/multi-auto-complete/index.ts
packages/devui-vue/devui/multi-auto-complete/src/multi-auto-complete-types.ts
packages/devui-vue/devui/multi-auto-complete/src/multi-auto-complete.scss
packages/devui-vue/devui/multi-auto-complete/src/multi-auto-complete.tsx
packages/devui-vue/docs/components/multi-auto-complete/index.md

feat(multi-auto-complete): 初始化组件

---

packages/devui-vue/devui/form/src/components/form-control/form-control.scss
packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
packages/devui-vue/devui/form/src/components/form-control/use-form-control.ts
packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
packages/devui-vue/devui/form/src/components/form-label/form-label-types.ts
packages/devui-vue/devui/form/src/components/form-label/form-label.tsx
packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
packages/devui-vue/devui/form/src/components/form-operation/form-operation.tsx
packages/devui-vue/devui/form/src/composables/use-field-collection.ts
packages/devui-vue/devui/form/src/composables/use-form-validation.ts
packages/devui-vue/devui/form/src/form-types.ts
packages/devui-vue/devui/form/src/form.tsx
packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/input/src/input.tsx
packages/devui-vue/docs/components/form/index.md

feat(Form): 完成基本的校验功能

---

packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts

feat(Form): 表单项的必填红色星号标志可以正确被设置

feat(Form): 表单项的必填红色星号标志可以正确被设置

---

packages/devui-vue/devui/form/index.ts
packages/devui-vue/devui/form/src/components/form-control/form-control.scss
packages/devui-vue/devui/form/src/components/form-item/form-item.scss
packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
packages/devui-vue/devui/form/src/components/form-label/form-label.scss
packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
packages/devui-vue/docs/components/form/index.md

feat(Form): 优化校验结果的样式&优化文档

---

packages/devui-vue/devui/card/src/card.tsx
packages/devui-vue/devui/read-tip/index.ts
packages/devui-vue/devui/read-tip/src/read-tip.tsx
packages/devui-vue/docs/components/card/index.md
packages/devui-vue/docs/components/read-tip/index.md
packages/devui-vue/docs/components/ripple/index.md

docs: 优化部分组件文档

---

packages/devui-vue/devui/auto-complete/src/auto-complete.scss

fix(auto-complete): 修复input宽度没有自适应的bug

---

packages/devui-vue/devui/list/src/list-item.scss

style(List): ListItem组件增加垂直居中的样式

style(List): ListItem组件增加垂直居中的样式

---

packages/devui-vue/devui/progress/__tests__/progress.spec.ts
packages/devui-vue/devui/progress/src/progress.tsx
packages/devui-vue/devui/shared/utils/index.ts
packages/devui-vue/devui/shared/utils/middle-num.ts

修复percentage属性值越界时产生的显示渲染错误 （[#492](https://github.com/DevCloudFE/vue-devui/issues/492)）

fix(Progress): 修复percentage属性值越界时产生的显示渲染错误

---

packages/devui-vue/devui/progress/src/progress-types.ts
packages/devui-vue/devui/progress/src/progress.tsx

refactor(Progress): 给一些具有any的类型添加具体类型

---

packages/devui-vue/devui/search/src/composables/use-search-class.ts
packages/devui-vue/devui/search/src/search-types.ts
packages/devui-vue/devui/search/src/search.tsx
packages/devui-vue/docs/components/search/index.md

Search 搜索框-组件设置maxLength不生效，因为props没有传递到 input 组件。

fix(search): search 组件设置 maxLength 不生效 （#485）

---

packages/devui-vue/docs/components/date-picker/index.md

docs(DatePicker): 修正DatePicker文档格式。

docs(DatePicker): 修正DatePicker文档格式 (#544)。

---

packages/devui-vue/devui/button/src/button.scss
packages/devui-vue/devui/button/src/use-button.ts

修复 Button 组件在loading状态时不应该有hover和active效果

fix(Button): 修复 Button 组件在loading状态时不应该有hover和active效果 (#558)。

---

packages/devui-vue/devui/checkbox/index.ts

fix(Checkbox): 修复没有导出CheckboxGroup的问题

fix(Checkbox): 修复没有导出CheckboxGroup的问题

---

packages/devui-vue/devui/fullscreen/src/fullscreen.tsx
packages/devui-vue/devui/fullscreen/src/utils.ts
packages/devui-vue/docs/components/fullscreen/index.md

+ fix(Fullscreen): 修复 Fullscreen 组件中 ts 警告。
+ docs(Fullscreen): 修正 Fullscreen 文档，沉浸式全屏无需设置 z-index 属性。

fix(Fullscreen): 修复 Fullscreen 组件中 ts 警告。

---

packages/devui-vue/devui/button/src/button.scss

fix(Button): Button组件的outline形态hover效果缺少动效 (#573)。

---

packages/devui-vue/devui/loading/src/loading.scss

fix(Loading): Loading 组件动效的卡顿感 (#571)。

---

packages/devui-vue/devui/rate/__tests__/rate.spec.ts
packages/devui-vue/devui/rate/src/rate.scss
packages/devui-vue/devui/rate/src/rate.tsx

fix(Rate): 修复`type`属性下`color`属性失效问题（[#488 ](https://github.com/DevCloudFE/vue-devui/issues/488)）

fix(Rate): 修复`type`属性下`color`属性失效问题

---

packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
packages/devui-vue/devui/form/src/composables/use-form-validation.ts
packages/devui-vue/devui/form/src/form-types.ts
packages/devui-vue/devui/form/src/form.tsx
packages/devui-vue/docs/components/form/index.md

feat(Form): 新增移除校验结果和重置值的方法

---

packages/devui-vue/devui/cascader/components/cascader-tag/index.scss
packages/devui-vue/devui/cascader/components/cascader-tag/index.tsx

修复Cascader组件中class与Tag组件class重名导致tag组件样式异常。

fix(Cascader): 修复Cascader组件中class与Tag组件class重名导致tag组件样式异常 (close #582) 。

---

packages/devui-vue/devui/popover/src/popover-types.ts
packages/devui-vue/devui/popover/src/popover.tsx
packages/devui-vue/devui/popover/src/use-popover.ts

fix(Popover): 鼠标移入Popover内Popover不应关闭

fix(Popover): 鼠标移入Popover内Popover不应关闭

---

packages/devui-vue/devui/input/src/composables/use-input-event.ts
packages/devui-vue/devui/input/src/composables/use-input-render.ts
packages/devui-vue/devui/input/src/input-types.tsx
packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/input/src/input.tsx
packages/devui-vue/devui/style/core/_form.scss
packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
packages/devui-vue/docs/components/input/index.md

refactor(Input): 重构Input组件代码

---

packages/devui-vue/devui/tooltip/src/tooltip-types.ts
packages/devui-vue/devui/tooltip/src/tooltip.tsx
packages/devui-vue/devui/tooltip/src/use-tooltip.ts
packages/devui-vue/docs/components/tooltip/index.md

fix(Tooltip): 修复鼠标不能移入到内容上的问题

---

packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
packages/devui-vue/devui/form/src/form-types.ts
packages/devui-vue/devui/form/src/form.tsx
packages/devui-vue/docs/components/form/index.md

feat(Form): 支持validate事件&支持配置rules变更后立即触发校验

feat(Form): 支持validate事件&支持配置rules变更后立即触发校验

---

packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributor.vue

chore: 修复PageContributor警告信息

---

packages/devui-vue/devui/alert/src/alert.scss
packages/devui-vue/devui/alert/src/alert.tsx
packages/devui-vue/devui/alert/src/components/alert-type-icon.tsx

refactor(Alert): 重构样式命名

---

packages/devui-vue/devui/auto-complete/src/auto-complete.scss
packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx

refactor(AutoComplete): 重构样式命名

refactor(AutoComplete): 重构样式命名

---

packages/devui-vue/devui/avatar/src/avatar.scss
packages/devui-vue/devui/avatar/src/avatar.tsx

refactor(Avatar): 重构样式命名

---

packages/devui-vue/devui/back-top/src/back-top.scss
packages/devui-vue/devui/back-top/src/back-top.tsx

refactor(BackTop): 重构样式命名

---

packages/devui-vue/devui/badge/src/badge.scss
packages/devui-vue/devui/badge/src/badge.tsx

refactor(Badge): 重构样式命名

---

packages/devui-vue/devui/breadcrumb/src/breadcrumb-item.scss
packages/devui-vue/devui/breadcrumb/src/breadcrumb-item.tsx
packages/devui-vue/devui/breadcrumb/src/breadcrumb.scss
packages/devui-vue/devui/breadcrumb/src/breadcrumb.tsx

refactor(Breadcrumb): 重构样式命名

---

packages/devui-vue/devui/button/src/button.scss
packages/devui-vue/devui/button/src/use-button.ts

refactor(Button): 重构样式命名

---

packages/devui-vue/devui/card/src/card.scss
packages/devui-vue/devui/card/src/card.tsx

refactor(Card): 重构样式命名

---

packages/devui-vue/devui/carousel/src/carousel.scss
packages/devui-vue/devui/carousel/src/carousel.tsx
packages/devui-vue/devui/carousel/src/item.tsx
packages/devui-vue/docs/components/carousel/index.md

refactor(Carousel): 重构样式命名

---

packages/devui-vue/devui/checkbox/src/checkbox.scss
packages/devui-vue/devui/checkbox/src/checkbox.tsx
packages/devui-vue/devui/input/src/composables/use-input-render.ts

refactor(Checkbox): 重构样式命名

---

packages/devui-vue/devui/fullscreen/src/fullscreen.scss
packages/devui-vue/devui/fullscreen/src/utils.ts

refactor(FullScreen): 重构样式命名

---

packages/devui-vue/devui/overlay/src/base-overlay.scss
packages/devui-vue/devui/overlay/src/base-overlay.tsx
packages/devui-vue/devui/overlay/src/fixed-overlay/fixed-overlay.scss
packages/devui-vue/devui/overlay/src/fixed-overlay/use-fixed-overlay.ts
packages/devui-vue/devui/overlay/src/flexible-overlay/flexible-overlay.scss
packages/devui-vue/devui/overlay/src/flexible-overlay/index.tsx

refactor(Overlay): 重构样式命名

---

packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/search/src/composables/use-search-class.ts
packages/devui-vue/devui/search/src/search.scss
packages/devui-vue/devui/search/src/search.tsx

refactor(Search): 重构样式命名

---

packages/devui-vue/devui/radio/src/radio-group.tsx
packages/devui-vue/devui/radio/src/radio.scss
packages/devui-vue/devui/radio/src/radio.tsx

refactor(Radio): 重构样式命名

---

packages/devui-vue/devui/select/src/select.scss
packages/devui-vue/devui/select/src/select.tsx

refactor(Select): 重构样式命名

---

packages/devui-vue/devui/textarea/src/textarea.scss
packages/devui-vue/devui/textarea/src/textarea.tsx

refactor(Textarea): 重构样式命名

---

packages/devui-vue/devui/switch/src/switch.scss
packages/devui-vue/devui/switch/src/switch.tsx

refactor(Switch): 重构样式命名

---

packages/devui-vue/devui/slider/src/slider.scss
packages/devui-vue/devui/slider/src/slider.tsx

refactor(Slider): 重构样式命名

---

packages/devui-vue/devui/upload/src/upload.scss
packages/devui-vue/devui/upload/src/upload.tsx

refactor(Upload): 重构样式命名

---

packages/devui-vue/devui/list/src/list-item.scss
packages/devui-vue/devui/list/src/list-item.tsx
packages/devui-vue/devui/list/src/list.tsx

refactor(List): 重构样式命名

---

packages/devui-vue/devui/image-preview/src/image-preview.scss
packages/devui-vue/devui/image-preview/src/image-preview.tsx

refactor(ImagePreview): 重构样式命名

refactor(ImagePreview): 重构样式命名

---

packages/devui-vue/devui/accordion/src/accordion.tsx

refactor(Accordion): 重构样式命名

---

packages/devui-vue/devui/status/src/status.scss
packages/devui-vue/devui/status/src/status.tsx

refactor(Status): 重构样式命名

---

packages/devui-vue/devui/skeleton/src/skeleton.tsx

refactor(Skeleton): 重构样式命名

---

packages/devui-vue/devui/rate/src/rate.scss
packages/devui-vue/devui/rate/src/rate.tsx

refactor(Rate): 重构样式命名

---

packages/devui-vue/devui/alert/src/alert.tsx
packages/devui-vue/devui/alert/src/components/alert-close-icon.tsx
packages/devui-vue/devui/alert/src/components/alert-type-icon.tsx

Alert 组件 icon 组件 ts 类型错误。不应该是 unknown。

fix(Alert): icon 组件 ts 类型错误。

---

packages/devui-vue/devui/tag/src/composables/use-class.ts
packages/devui-vue/devui/tag/src/tag.scss
packages/devui-vue/devui/tag/src/tag.tsx

refactor(Tag): 重构样式命名

---

packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts

fix(AutoComplete): 修复重构样式带来的测试错误

fix(AutoComplete): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/avatar/__tests__/avatar.spec.ts

fix(Avatar): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/drawer/src/components/drawer-overlay.scss
packages/devui-vue/devui/drawer/src/components/drawer-overlay.tsx
packages/devui-vue/devui/drawer/src/drawer.scss
packages/devui-vue/devui/drawer/src/use-drawer.ts

refactor(Drawer): 重构样式命名

---

packages/devui-vue/devui/loading/__tests__/loading.spec.ts
packages/devui-vue/devui/loading/src/loading.scss
packages/devui-vue/devui/loading/src/loading.tsx

refactor(Loading): 重构样式命名

---

packages/devui-vue/devui/modal/src/components/body.tsx
packages/devui-vue/devui/modal/src/components/footer.tsx
packages/devui-vue/devui/modal/src/components/header.tsx
packages/devui-vue/devui/modal/src/modal.scss
packages/devui-vue/devui/modal/src/modal.tsx

refactor(Modal): 重构样式命名

---

packages/devui-vue/devui/tooltip/src/tooltip.scss
packages/devui-vue/devui/tooltip/src/tooltip.tsx

refactor(Tooltip): 重构样式命名

---

packages/devui-vue/devui/progress/src/progress.scss
packages/devui-vue/devui/progress/src/progress.tsx

refactor(Progress): 重构样式命名

---

packages/devui-vue/devui/popover/src/popover-icon.scss
packages/devui-vue/devui/popover/src/popover-icon.tsx
packages/devui-vue/devui/popover/src/popover-icons.tsx
packages/devui-vue/devui/popover/src/popover.scss
packages/devui-vue/devui/popover/src/popover.tsx

refactor(Popover): 重构样式命名

---

packages/devui-vue/devui/notification/src/notification-icon-close.tsx
packages/devui-vue/devui/notification/src/notification-icons.tsx
packages/devui-vue/devui/notification/src/notification-image.tsx
packages/devui-vue/devui/notification/src/notification.scss
packages/devui-vue/devui/notification/src/notification.tsx

refactor(Notification): 重构样式命名

refactor(Notification): 重构样式命名

---

packages/devui-vue/devui/pagination/src/components/config-menu.tsx
packages/devui-vue/devui/pagination/src/components/jump-page.tsx
packages/devui-vue/devui/pagination/src/components/page-nums.tsx
packages/devui-vue/devui/pagination/src/pagination.scss
packages/devui-vue/devui/pagination/src/pagination.tsx

refactor(Pagination): 重构样式命名

---

packages/devui-vue/devui/dropdown/src/dropdown-menu.tsx
packages/devui-vue/devui/dropdown/src/dropdown.scss
packages/devui-vue/devui/dropdown/src/dropdown.tsx

refactor(Dropdown): 重构样式命名

---

packages/devui-vue/devui/layout/src/aside.tsx
packages/devui-vue/devui/layout/src/content.scss
packages/devui-vue/devui/layout/src/content.tsx
packages/devui-vue/devui/layout/src/footer.scss
packages/devui-vue/devui/layout/src/footer.tsx
packages/devui-vue/devui/layout/src/header.scss
packages/devui-vue/devui/layout/src/header.tsx
packages/devui-vue/devui/layout/src/layout.scss
packages/devui-vue/devui/layout/src/layout.tsx

refactor(Layout): 重构样式命名

---

packages/devui-vue/devui/tabs/src/tab.tsx
packages/devui-vue/devui/tabs/src/tabs.scss
packages/devui-vue/devui/tabs/src/tabs.tsx

refactor(Tabs): 重构样式命名

---

packages/devui-vue/devui/steps-guide/src/steps-guide.scss
packages/devui-vue/devui/steps-guide/src/steps-guide.tsx

refactor(StepsGuide): 重构样式命名

---

packages/devui-vue/devui/splitter/src/components/splitter-bar.scss
packages/devui-vue/devui/splitter/src/components/splitter-bar.tsx
packages/devui-vue/devui/splitter/src/components/splitter-pane.scss
packages/devui-vue/devui/splitter/src/components/splitter-pane.tsx
packages/devui-vue/devui/splitter/src/splitter.scss
packages/devui-vue/devui/splitter/src/splitter.tsx

refactor(Splitter): 重构样式命名

---

packages/devui-vue/devui/button/__tests__/button-group.spec.tsx
packages/devui-vue/devui/button/index.ts
packages/devui-vue/devui/button/src/button-group.scss
packages/devui-vue/devui/button/src/button-group.tsx
packages/devui-vue/devui/button/src/button-types.ts
packages/devui-vue/devui/button/src/use-button.ts
packages/devui-vue/docs/components/button/index.md

feat(buttonGroup): 增加 button-group 组件 (close #568);

---

packages/devui-vue/devui/modal/src/modal.scss
packages/devui-vue/devui/modal/src/modal.tsx

fix(Modal): 移除样式前缀

---

packages/devui-vue/devui/popover/src/popover.scss
packages/devui-vue/devui/popover/src/popover.tsx

fix(Popover): 移除popover中的样式前缀

---

packages/devui-vue/devui/tabs/src/tabs.scss

style(Tabs): 动画采用样式变量&间距需为4的倍数

style(Tabs): 动画采用样式变量&间距需为4的倍数

---

packages/devui-vue/devui/skeleton/src/components/skeleton-item.scss
packages/devui-vue/devui/skeleton/src/components/skeleton-item.tsx

refactor(Skeleton): 重构样式前缀

---

packages/devui-vue/devui/select/src/select.tsx

fix(Select): 事采用中划线件命名

---

packages/devui-vue/devui/switch/src/switch.scss

style(Switch): 修复动画的样式变量

---

packages/devui-vue/devui/button/__tests__/button.spec.tsx
packages/devui-vue/devui/button/src/button-types.ts
packages/devui-vue/devui/button/src/button.scss
packages/devui-vue/devui/button/src/use-button.ts
packages/devui-vue/docs/components/button/index.md
packages/devui-vue/jest.config.js

添加shape属性，值为： circle/round  用于支持圆角和圆形图标按钮

feat(button): button添加shape属性

---

packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
packages/devui-vue/devui/checkbox/src/checkbox-types.ts
packages/devui-vue/devui/checkbox/src/checkbox.scss
packages/devui-vue/devui/checkbox/src/checkbox.tsx
packages/devui-vue/docs/components/checkbox/index.md

fix(Checkbox): 参数halfchecked改成half-checked

fix(Checkbox): 参数halfchecked改成half-checked

---

packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/devui/table/src/table.scss
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

feat(Table): 支持配置空数据文本/模板

---

packages/devui-vue/devui/alert/__tests__/alert.spec.ts
packages/devui-vue/devui/shared/hooks/use-namespace.ts

refactor(Alert): 抽离测试样式
`useNamespace` 方法添加是否为样式添加 ` . ` 前缀

refactor(Alert): 抽离测试样式

---

packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/devui/table/src/components/header/header.scss
packages/devui-vue/devui/table/src/composables/use-table.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 支持设置单元格内容水平对齐方式

---

packages/devui-vue/devui/badge/__tests__/badge.spec.ts

fix(Badge): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/breadcrumb/__tests__/breadcrumb.spec.ts

fix(Breadcrumb): 修复重构样式带来的测试错误

fix(Breadcrumb): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/card/__tests__/__snapshots__/card.spec.ts.snap
packages/devui-vue/devui/card/__tests__/card.spec.ts

fix(Card): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/carousel/__tests__/carousel.spec.ts

fix(Carousel): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx

fix(Dropdown): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
packages/devui-vue/devui/editable-select/src/editable-select.tsx

fix(EditableSelect): 修复测试错误

---

packages/devui-vue/devui/fullscreen/__tests__/fullscreen.spec.ts

fix(Fullscreen): 修复测试错误并新增属性测试

fix(Fullscreen): 修复测试错误并新增属性测试

---

packages/devui-vue/devui/grid/__tests__/grid.spec.tsx
packages/devui-vue/devui/grid/src/col.tsx
packages/devui-vue/devui/grid/src/composables/use-grid.ts
packages/devui-vue/devui/grid/src/composables/use-screen.ts
packages/devui-vue/devui/grid/src/row.tsx

fix(Grid): 修复重构样式带来的测试错误

---

packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/devui/table/src/composables/use-table.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 组件样式宽高等样式优化

---

packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/src/components/body/body-types.ts
packages/devui-vue/devui/table/src/components/body/body.tsx
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

feat(Table): 支持单元格点击事件

---

packages/devui-vue/devui/table/src/components/column/column.tsx
packages/devui-vue/devui/table/src/components/column/config.tsx
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/store/store-types.ts
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

Updates:
1. 重构table固定列的demo，去掉多余的no-data的demo
2. 重构d-column子组件，将render合并到setup，并优化表头分组的逻辑
3. 给d-table组件增加`check-change`和`check-all-change`事件，并补充demo个文档

feat(table): add table check event

---

packages/devui-vue/docs/contributing/index.md

docs: update contributing doc

---

packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts

refactor(AutoComplete): 抽离测试样式

refactor(AutoComplete): 抽离测试样式

---

packages/devui-vue/devui/avatar/__tests__/avatar.spec.ts

refactor(Avatar): 抽离测试样式

---

packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/src/components/fix-header.tsx
packages/devui-vue/devui/table/src/components/normal-header.tsx
packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 支持配置是否显示表头

---

packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 增加row-key参数

---

packages/devui-vue/devui/select/__tests__/select.spec.tsx
packages/devui-vue/devui/select/src/select-types.ts
packages/devui-vue/devui/select/src/select.tsx
packages/devui-vue/devui/select/src/use-select.ts
packages/devui-vue/docs/components/select/index.md

1、添加select-types.ts移植原useSect.ts功能
2、拆分select.stx组件，去除render, 逻辑放入useSelect.ts
3、单元测试修改，全部通过

refactor(select): 重构select组件

---

packages/devui-vue/devui/checkbox/__tests__/checkbox-group.spec.ts
packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
packages/devui-vue/devui/checkbox/src/checkbox-types.ts
packages/devui-vue/devui/checkbox/src/checkbox.tsx
packages/devui-vue/docs/components/checkbox/index.md

d-checkbox-group添加可被勾选的最大数量max

feat(checkbox-group): checkbox-group add select max limit

---

packages/devui-vue/devui/breadcrumb/__tests__/breadcrumb.spec.ts

refactor(Breadcrumb): 抽离测试样式

---

packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.tsx
packages/devui-vue/devui/tooltip/src/tooltip-types.ts
packages/devui-vue/devui/tooltip/src/tooltip.tsx
packages/devui-vue/devui/tooltip/src/use-tooltip.ts
packages/devui-vue/docs/components/tooltip/index.md

1、disabled：Tooltip是否可用
2、enterable：鼠标能否进入到tooltip中
3、hide-after：tooltip出现后，自动隐藏延时，单位毫秒，为0则不会自动隐藏

feat(tooltip): add disabled enterable hide-after

---

packages/devui-vue/devui/tabs/src/tab.tsx
packages/devui-vue/devui/tabs/src/tabs.tsx

fix(Tabs): 修复Tabs组件插槽内容为空时渲染错误

fix(Tabs): 修复Tabs组件插槽内容为空时渲染错误

---

packages/devui-vue/devui/table/src/table.scss

feat(Table): Table不同大小对应不同字号

---

packages/devui-vue/devui/comment/src/comment-types.ts
packages/devui-vue/devui/comment/src/comment.scss
packages/devui-vue/devui/comment/src/comment.tsx
packages/devui-vue/devui/shared/utils/url.ts
packages/devui-vue/docs/components/comment/index.md

Update:
1. render中的逻辑移到setup，增加`useNamespace`处理
2. 增加`自定义`的demo
3. 增加`Comment 参数`的api
4. 优化Comment组件样式
5. 移除空文件`get-slot.ts`

refactor(comment): 重构代码并完善demo和api文档

---

packages/devui-vue/devui/icon/src/const.ts
packages/devui-vue/devui/icon/src/icon-types.ts
packages/devui-vue/devui/icon/src/icon.scss
packages/devui-vue/devui/icon/src/icon.tsx
packages/devui-vue/devui/icon/src/svg-icon.tsx
packages/devui-vue/docs/components/icon/index.md

update:
1. 支持svg图标
2. 重构代码，将字体图标、图片、svg图标抽取成变量形式

refactor(icon): 重构icon组件并支持svg图标

---

packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/column.tsx
packages/devui-vue/docs/components/table/index.md

update:
1. 增加行勾选控制功能 checkable

feat(table): add table checkable

---

packages/devui-vue/docs/components/button/index.md

fix(button): 修复button组件demo报错问题

---

packages/devui-vue/devui/table/__tests__/table.spec.tsx
packages/devui-vue/devui/table/src/components/body-td/body-td-types.ts
packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
packages/devui-vue/devui/table/src/components/body-td/use-body-td.ts
packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 支持单元格内容过长隐藏时显示tooltip

feat(Table): 支持单元格内容过长隐藏时显示tooltip

---

packages/devui-vue/devui/icon/src/icon.tsx

fix(Icon): 移除Icon组件的空根节点

---

packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/column.tsx
packages/devui-vue/devui/table/src/components/column/config.tsx
packages/devui-vue/devui/table/src/store/store-types.ts
packages/devui-vue/docs/components/table/index.md

update:
1. 实现根据index来标识行数据的reserve-check

feat(table): 支持基础版本reserve-check勾选状态保留功能

---

packages/devui-vue/devui/avatar/__tests__/avatar.spec.ts
packages/devui-vue/devui/avatar/src/avatar.tsx

fix(Avatar): 修复由于`gender`属性值错误抛出的异常改为警告

fix(Avatar): 修复由于`gender`属性值错误抛出的异常改为警告

---

packages/devui-vue/devui/dropdown/src/dropdown-menu.tsx
packages/devui-vue/devui/dropdown/src/dropdown.scss
packages/devui-vue/devui/dropdown/src/dropdown.tsx
packages/devui-vue/devui/tooltip/src/tooltip.scss
packages/devui-vue/devui/tooltip/src/tooltip.tsx

style: 修改漏掉的样式前缀

---

packages/devui-vue/devui/table/src/components/body-td/use-body-td.ts

fix(Table): 修复监听单元格变化时range报错问题

fix(Table): 修复监听单元格变化时range报错问题

---

packages/devui-vue/devui/card/__tests__/card.spec.ts

refactor(Card): 抽离测试样式

---

packages/devui-theme/src/theme-collection/extend-theme.ts

fix(Theme): 新增追光主题样式变量

---

packages/devui-vue/devui/form/src/components/form-control/form-control.scss
packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
packages/devui-vue/devui/form/src/components/form-label/form-label.tsx

fix(Form): 修复Form中popover的用法

---

packages/devui-vue/devui/tabs/src/tabs-types.ts
packages/devui-vue/devui/tabs/src/tabs.tsx
packages/devui-vue/devui/tabs/src/use-tabs.ts

fix(Tabs): 修复type属性值变更后，视图不刷新的问题

fix(Tabs): 修复type属性值变更后，视图不刷新的问题

---

packages/devui-vue/devui/rate/src/rate.tsx

fix(Rate): 修复modelValue,count属性变更后视图不更新问题

fix(Rate): 修复modelValue,count属性变更后视图不更新问题

---

packages/devui-vue/devui/input-number/src/input-number-types.ts
packages/devui-vue/devui/input-number/src/input-number.scss
packages/devui-vue/devui/input-number/src/input-number.tsx
packages/devui-vue/devui/input-number/src/use-input-number.ts
packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts

refactor(InputNumber): 重构代码结构

---

packages/devui-vue/devui/checkbox/__tests__/checkbox-button.spec.ts
packages/devui-vue/devui/checkbox/__tests__/checkbox-group.spec.ts
packages/devui-vue/devui/checkbox/index.ts
packages/devui-vue/devui/checkbox/src/checkbox-button.scss
packages/devui-vue/devui/checkbox/src/checkbox-button.tsx
packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
packages/devui-vue/devui/checkbox/src/checkbox-types.ts
packages/devui-vue/devui/checkbox/src/use-checkbox.ts
packages/devui-vue/docs/components/checkbox/index.md

1、添加的checkbox-button基本属性
2、更改checkbox-group为插槽形式
3、添加checkbox-group的text-color更改按钮形式的active颜色

 feat(checkbox-button): checkbox-button feature

---

packages/devui-vue/devui/menu/src/components/menu-item.tsx
packages/devui-vue/devui/menu/src/components/menu-transition.tsx
packages/devui-vue/devui/menu/src/components/sub-menu.tsx
packages/devui-vue/devui/menu/src/helper/init-select.ts
packages/devui-vue/devui/menu/src/helper/layer-composables.ts
packages/devui-vue/devui/menu/src/styles/vertical.scss

- vertical模式下的动画优化
- 修改了```useInitSelect```的名称错误

fix(menu): vertical模式下动画优化

---

packages/devui-vue/devui/comment/src/comment-types.ts
packages/devui-vue/devui/comment/src/comment.tsx
packages/devui-vue/docs/components/comment/index.md

refactor(comment): remove comment actions

---

packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/body/body.tsx
packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/column.tsx
packages/devui-vue/devui/table/src/components/column/config.tsx
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/devui/table/src/components/header/header.tsx
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/store/store-types.ts
packages/devui-vue/docs/components/table/index.md

update:
1. 给`d-column`增加`type="expand"`，实现展开行功能
效果如下：

feat(table): 增加表格展开行功能 expand

---

packages/devui-vue/devui/input-number/src/input-number-icons.tsx
packages/devui-vue/devui/input-number/src/input-number-types.ts
packages/devui-vue/devui/input-number/src/input-number.scss
packages/devui-vue/devui/input-number/src/input-number.tsx
packages/devui-vue/devui/input-number/src/use-input-number.ts
packages/devui-vue/devui/shared/utils/index.ts
packages/devui-vue/devui/shared/utils/is.ts
packages/devui-vue/docs/components/input-number/index.md

feat(InputNumber): 新增精度参数&Input框相关方法

feat(InputNumber): 新增精度参数&Input框相关方法

---

packages/devui-vue/devui/form/index.ts
packages/devui-vue/devui/form/src/components/form-control/use-form-control.ts
packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
packages/devui-vue/docs/components/form/index.md

refactor(Form): Form使用结构变更，简化为d-form&d-form-item两层

refactor(Form): Form使用结构变更，简化为d-form&d-form-item两层

---

packages/devui-vue/devui/input-number/src/input-number.tsx
packages/devui-vue/devui/input-number/src/use-input-number.ts

fix(InputNumber): 修复交互问题

---

packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts

补充`table`/`select`/`input`/`auto-complete`/`checkbox`等等多个组件的贡献者信息

docs: 补充组件的贡献者信息

---

packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
packages/devui-vue/docs/components/form/index.md

fix(Form): 移除文档demo中的d-tag-input控件

fix(Form): 移除文档demo中的d-tag-input控件

---

packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx

[test(InputNumber): 补充InputNumber测试用例](https://github.com/DevCloudFE/vue-devui/commit/dc62508692a55d2dfb5a745a4b35944f5223617e)

test(InputNumber): 补充InputNumber测试用例

---

packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/modal/src/composables/use-modal.ts
packages/devui-vue/devui/modal/src/modal-types.ts
packages/devui-vue/devui/modal/src/modal.tsx
packages/devui-vue/docs/components/modal/index.md

feat(Modal): 新增escapable & showClose参数

feat(Modal): 新增escapable & showClose参数

---

packages/devui-vue/devui/auto-complete/src/auto-complete.scss
packages/devui-vue/devui/auto-complete/src/auto-complete.tsx

fix(AutoComplete): 修复禁用态样式问题&移除下拉菜单的箭头

fix(AutoComplete): 修复禁用态样式问题&移除下拉菜单的箭头

---

packages/devui-vue/devui/radio/__tests__/radio-group.spec.ts
packages/devui-vue/devui/radio/__tests__/radio.spec.ts
packages/devui-vue/devui/radio/src/radio-group.scss
packages/devui-vue/devui/radio/src/radio-types.ts
packages/devui-vue/devui/radio/src/radio.scss
packages/devui-vue/devui/radio/src/radio.tsx
packages/devui-vue/devui/radio/src/use-radio.ts
packages/devui-vue/docs/components/radio/index.md

1、添加d-radio的border、size属性
2、添加d-radio-group的border、size属性
3、使用文档更改相同名称的变量和方法

feat(radio): radio border size

---

packages/devui-vue/devui/table/src/components/filter/filter.scss
packages/devui-vue/devui/table/src/components/header/header.scss
packages/devui-vue/devui/table/src/components/sort/sort.scss
packages/devui-vue/devui/table/src/components/sort/sort.tsx

fix(Table): 更新过滤和排序图标样式&排序图标增加命名前缀

fix(Table): 更新过滤和排序图标样式&排序图标增加命名前缀

---

packages/devui-vue/devui/overlay/src/fixed-overlay/fixed-overlay-types.ts
packages/devui-vue/devui/overlay/src/fixed-overlay/fixed-overlay.scss
packages/devui-vue/devui/overlay/src/fixed-overlay/index.tsx
packages/devui-vue/devui/overlay/src/fixed-overlay/use-fixed-overlay.ts
packages/devui-vue/docs/components/overlay/index.md

refactor(FixedOverlay): 重构FixedOverlay

refactor(FixedOverlay): 重构FixedOverlay

---

packages/devui-vue/devui/radio/__tests__/radio-button.spec.ts
packages/devui-vue/devui/radio/__tests__/radio-group.spec.ts
packages/devui-vue/devui/radio/index.ts
packages/devui-vue/devui/radio/src/radio-button.scss
packages/devui-vue/devui/radio/src/radio-button.tsx
packages/devui-vue/devui/radio/src/radio-types.ts
packages/devui-vue/devui/radio/src/use-radio.ts
packages/devui-vue/docs/components/radio/index.md

1、添加d-radio-button组件以及它的value、disabled、name属性
2、添加d-radio-group的按钮形态属性fill、text-color

feat(radio):  add d-radio-button

---

packages/devui-vue/devui/modal/src/composables/use-modal.ts
packages/devui-vue/devui/modal/src/modal-types.ts
packages/devui-vue/devui/modal/src/modal.scss
packages/devui-vue/devui/modal/src/modal.tsx
packages/devui-vue/docs/components/modal/index.md

feat(Modal): 新增show-overlay&append-to-body参数&优化动画效果

feat(Modal): 新增show-overlay&append-to-body参数&优化动画效果

---

packages/devui-vue/docs/components/modal/index.md

fix(Modal): 移除服务方式创建Modal的demo案例

fix(Modal): 移除服务方式创建Modal的demo案例

---

packages/devui-vue/devui/radio/src/radio-button.scss
packages/devui-vue/devui/radio/src/radio.scss

refactor(radio): refactor radio css

---

packages/devui-vue/devui/checkbox/src/checkbox-button.scss
packages/devui-vue/devui/checkbox/src/checkbox.scss

refactor(checkbox): refactor checkbox css var

---

packages/devui-vue/devui/tag/__tests__/tag.spec.ts
packages/devui-vue/devui/tag/src/composables/use-class.ts
packages/devui-vue/devui/tag/src/tag-types.ts
packages/devui-vue/devui/tag/src/tag.scss
packages/devui-vue/docs/components/tag/index.md

feat(tag): add tag size

---

packages/devui-vue/devui/form/index.ts
packages/devui-vue/devui/form/src/form-types.ts
packages/devui-vue/devui/input/src/composables/use-input-render.ts
packages/devui-vue/devui/input/src/input-types.tsx
packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/input/src/input.tsx
packages/devui-vue/docs/components/form/index.md

feat(Form): 增加disabled&size参数，已适配Input组件

feat(Form): 增加disabled&size参数，已适配Input组件

---

packages/devui-vue/devui/switch/__tests__/switch.spec.ts
packages/devui-vue/devui/switch/src/switch-types.ts
packages/devui-vue/devui/switch/src/use-switch.ts
packages/devui-vue/docs/components/switch/index.md

添加 switch开关的active-value、inactive-value属性

feat(switch): add active-value inactive-value

---

packages/devui-vue/docs/components/switch/index.md

refactor(switch): refactor switch docs

---

packages/devui-vue/devui/textarea/src/composables/use-textarea-event.ts
packages/devui-vue/devui/textarea/src/composables/use-textarea-render.ts
packages/devui-vue/devui/textarea/src/textarea-types.ts
packages/devui-vue/devui/textarea/src/textarea.scss
packages/devui-vue/devui/textarea/src/textarea.tsx
packages/devui-vue/docs/components/form/index.md

feat: Form集成Textarea组件，支持校验&disabled

feat: Form集成Textarea组件，支持校验&disabled

---

packages/devui-vue/devui/checkbox/src/use-checkbox.ts
packages/devui-vue/docs/components/form/index.md

feat(Form): 集成Checkbox，增加disabled&size&校验

feat(Form): 集成Checkbox，增加disabled&size&校验

---

packages/devui-vue/devui/steps/src/step.scss
packages/devui-vue/devui/steps/src/step.tsx

update:
1. 增加连接线
2. flexBasis根据步骤数量动态变化

feat(steps): 增加连接线

---

packages/devui-vue/devui/radio/src/use-radio.ts
packages/devui-vue/docs/components/form/index.md

feat(Form): 集成Radio，增加disabled&size&校验

feat(Form): 集成Radio，增加disabled&size&校验

---

packages/devui-vue/devui/switch/src/switch-types.ts
packages/devui-vue/devui/switch/src/switch.tsx
packages/devui-vue/devui/switch/src/use-switch.ts

feat(Form): 集成Switch，支持disabled&size

feat(Form): 集成Switch，支持disabled&size

---

packages/devui-vue/devui/select/src/components/select-content.tsx
packages/devui-vue/devui/select/src/composables/use-select-content.ts
packages/devui-vue/devui/select/src/select-types.ts
packages/devui-vue/devui/select/src/select.scss
packages/devui-vue/devui/select/src/select.tsx
packages/devui-vue/devui/select/src/use-select.ts
packages/devui-vue/docs/components/form/index.md

feat(Form): 集成Select，支持disabled&size&校验结果

feat(Form): 集成Select，支持disabled&size&校验结果

---

packages/devui-vue/devui/steps/src/const.ts
packages/devui-vue/devui/steps/src/step-types.ts
packages/devui-vue/devui/steps/src/step.scss
packages/devui-vue/devui/steps/src/step.tsx
packages/devui-vue/devui/steps/src/steps-types.ts
packages/devui-vue/devui/steps/src/steps.tsx
packages/devui-vue/docs/components/steps/index.md

update:
1. steps组件增加align-center
2. step组件增加description

feat(steps): add align-center and description

---

packages/devui-vue/devui/auto-complete/src/auto-complete.scss
packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx
packages/devui-vue/devui/auto-complete/src/composables/use-auto-complete-render.ts
packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
packages/devui-vue/devui/input/src/composables/use-input-render.ts
packages/devui-vue/devui/select/src/select.scss
packages/devui-vue/devui/textarea/src/composables/use-textarea-render.ts
packages/devui-vue/docs/components/form/index.md

feat(Form): 集成AutoComplete，支持disabled&size&校验

feat(Form): 集成AutoComplete，支持disabled&size&校验

---

packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
packages/devui-vue/docs/components/form/index.md

fix(Form): 修复resetField方法的问题

---

packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu-types.ts
packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
packages/devui-vue/devui/tabs/src/tabs.tsx
packages/devui-vue/docs/.vitepress/devui-theme/styles/demo-block.scss
packages/devui-vue/docs/components/menu/index.md
packages/devui-vue/docs/components/select/index.md
packages/devui-vue/docs/components/tabs/index.md

修复：
1、tabs，menu文档问题
2、tabs left、right布局时内容无法撑开
3、sub-menu disable=>disabled

fix(tabs/menu): 修复tabs，menu文档问题

---

packages/devui-vue/devui/time-picker/src/components/popup-line/composables/use-popup-line.ts
packages/devui-vue/devui/time-picker/src/components/popup-line/index.scss
packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
packages/devui-vue/devui/time-picker/src/components/time-popup/index.scss
packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
packages/devui-vue/devui/time-picker/src/components/time-scroll/composables/use-time-scroll.ts
packages/devui-vue/devui/time-picker/src/components/time-scroll/index.tsx
packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
packages/devui-vue/devui/time-picker/src/time-picker.scss
packages/devui-vue/devui/time-picker/src/time-picker.tsx
packages/devui-vue/devui/time-picker/src/types.ts
packages/devui-vue/devui/time-picker/src/utils.ts
packages/devui-vue/docs/components/time-picker/index.md

1、优化样式
2、修改eslint问题以及不规则命名
3、更改弹出层的显示隐藏时候的方式

refactor(time-picker):  refactor time-picker

---

packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
packages/devui-vue/devui/menu/src/menu.tsx
packages/devui-vue/devui/menu/src/styles/horizontal.scss
packages/devui-vue/devui/menu/src/styles/public.scss
packages/devui-vue/devui/menu/src/styles/vertical.scss
packages/devui-vue/docs/components/menu/index.md

1、sub-menu 属性disable => disabled
2、水平菜单时，sub-menu 点击不应该触发选中效果
3、menu-item 使用herf属性，点击无法跳转修复
4、水平菜单时，sub-menu添加箭头图标
5、垂直菜单时，sub-menu箭头变换动画优化
6、样式文件使用变量前缀
7、修复deselect事件：dseletc=>deselect

fix(menu): 功能问题修复及优化

---

packages/devui-vue/devui/steps/src/step-types.ts
packages/devui-vue/devui/steps/src/step.scss
packages/devui-vue/devui/steps/src/step.tsx
packages/devui-vue/devui/steps/src/steps-types.ts
packages/devui-vue/devui/steps/src/steps.scss
packages/devui-vue/devui/steps/src/steps.tsx
packages/devui-vue/docs/components/steps/index.md

update:
1. step增加icon属性和插槽，支持自定义图标
2. steps增加direction属性，支持竖向步骤条

feat(steps): add icon/direction props

---

packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
packages/devui-vue/devui/time-picker/src/components/popup-line/composables/use-popup-line.ts
packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
packages/devui-vue/devui/time-picker/src/components/time-popup/index.scss
packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
packages/devui-vue/devui/time-picker/src/time-picker-types.ts
packages/devui-vue/devui/time-picker/src/time-picker.scss
packages/devui-vue/devui/time-picker/src/time-picker.tsx
packages/devui-vue/devui/time-picker/src/types.ts
packages/devui-vue/devui/time-picker/src/utils.ts
packages/devui-vue/docs/components/time-picker/index.md

1、添加size属性
2、添加readonly属性
3、更改input组件为内部d-input组件
4、更改弹出层为内部d-overlay组件
5、修改之前的交互逻辑
6、修复之前format存在的bug

feat(time-picker):  add time-picker size format readonly

---

packages/devui-vue/devui/statistic/src/statistic-types.ts
packages/devui-vue/devui/statistic/src/statistic.scss
packages/devui-vue/devui/statistic/src/statistic.tsx
packages/devui-vue/docs/components/statistic/index.md

style(Statistic): 重构样式命名，移除value-style参数

style(Statistic): 重构样式命名，移除value-style参数

---

packages/devui-vue/devui/search/src/composables/use-search-keywords.ts

fix(Search): 修复点击清空按钮时不会触发search事件的问题

fix(Search): 修复点击清空按钮时不会触发search事件的问题

---

packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
packages/devui-vue/devui/time-select/index.ts
packages/devui-vue/devui/time-select/src/time-select-types.ts
packages/devui-vue/devui/time-select/src/time-select.tsx
packages/devui-vue/devui/time-select/src/use-time-select.ts
packages/devui-vue/docs/components/time-select/index.md
packages/devui-vue/jest.config.js

1、属性支持：size、placeholder、disabled、start、end、step、min-time、max-time、clearable
2、支持事件change、focus、blur

feat(time-select): add time-select

---

packages/devui-vue/devui/icon/src/icon.tsx
packages/devui-vue/devui/table/index.ts
packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/body/body.tsx
packages/devui-vue/devui/table/src/components/column/column.tsx
packages/devui-vue/devui/table/src/components/column/config.tsx
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/devui/table/src/composables/use-table.ts
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/store/store-types.ts
packages/devui-vue/devui/table/src/store/use-expand.ts
packages/devui-vue/devui/table/src/table-types.ts
packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/devui/table/src/utils.ts
packages/devui-vue/docs/components/table/index.md

feat(Table): 优化展开行逻辑，增加default-expand-all&expand-row-keys参数

feat(Table): 优化展开行逻辑，增加default-expand-all&expand-row-keys参数

---

packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/ThemePicker.vue
packages/devui-vue/docs/.vitepress/devui-theme/styles/layout.scss

feat(docs): 增加主题切换器

---

packages/devui-vue/devui/transfer/__tests__/transfer.spec.ts
packages/devui-vue/devui/transfer/src/components/transfer-body.tsx
packages/devui-vue/devui/transfer/src/components/transfer-panel.tsx
packages/devui-vue/devui/transfer/src/composables/use-transfer-body.ts
packages/devui-vue/devui/transfer/src/composables/use-transfer-header.ts
packages/devui-vue/devui/transfer/src/composables/use-transfer-panel.ts
packages/devui-vue/devui/transfer/src/composables/use-transfer.ts
packages/devui-vue/devui/transfer/src/transfer-types.ts
packages/devui-vue/devui/transfer/src/transfer.scss
packages/devui-vue/devui/transfer/src/transfer.tsx
packages/devui-vue/docs/components/transfer/index.md

feat(transfer): add render-content

---

packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
packages/devui-vue/devui/time-picker/src/components/time-popup/index.scss
packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
packages/devui-vue/devui/time-picker/src/components/time-scroll/index.tsx
packages/devui-vue/devui/time-picker/src/time-picker.tsx

refactor(time-picker): refactor time-picker class

---

packages/devui-vue/devui/countdown/src/countdown.tsx
packages/devui-vue/devui/countdown/src/utils.ts
packages/devui-vue/docs/components/countdown/index.md

https://blog.bitsrc.io/how-to-get-an-accurate-setinterval-in-javascript-ca7623d1d26a

fix: 使用精确定时器

---

packages/devui-vue/devui/cascader/__tests__/cascader.spec.ts
packages/devui-vue/devui/cascader/hooks/use-cascader.ts
packages/devui-vue/devui/cascader/src/cascader-types.ts
packages/devui-vue/devui/cascader/src/cascader.tsx
packages/devui-vue/docs/components/cascader/index.md

1、添加size属性
2、添加focus、blur事件
3、添加单元测试

feat(cascader): add size test

---

packages/devui-vue/devui/cascader/__tests__/cascader.spec.ts
packages/devui-vue/devui/cascader/components/cascader-item/index.scss
packages/devui-vue/devui/cascader/components/cascader-item/index.tsx
packages/devui-vue/devui/cascader/hooks/use-cascader.ts
packages/devui-vue/devui/cascader/hooks/use-filter.ts
packages/devui-vue/devui/cascader/src/cascader-types.ts
packages/devui-vue/devui/cascader/src/cascader.scss

refactor(cascader): refactor css use-filter

---

packages/devui-vue/devui/cascader/hooks/use-cascader-multiple.ts
packages/devui-vue/docs/components/cascader/index.md

refactor(cascader): 清理无用代码

---

packages/devui-vue/devui/transfer/src/composables/use-transfer-body.ts

fix(transfer): fix codecheck

---

packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/devui/tree/src/composables/use-core.ts
packages/devui-vue/devui/tree/src/composables/use-operate.ts

update:
1. 解决节点勾选不生效问题
2. 解决节点增删报错问题

fix(tree): 解决树节点勾选不生效和增删节点报错的问题

---

packages/devui-vue/devui/time-picker/src/time-picker.tsx

fix(time-picker): fix time-picker position

---

packages/devui-vue/devui/icon/src/composables/use-icon-dom.tsx
packages/devui-vue/devui/icon/src/icon.scss

fix(Icon): Icon组件样式问题，影响到Steps组件样式

---

packages/devui-vue/devui/image-preview/__tests__/image-preview.spec.ts
packages/devui-vue/devui/image-preview/src/image-preview.scss

fix(image-preview): 预览图片 去除button按钮边框 (close #993);

---

packages/devui-vue/devui/back-top/src/back-top.tsx
packages/devui-vue/devui/textarea/src/composables/use-textarea-event.ts
packages/devui-vue/devui/textarea/src/textarea.tsx
packages/devui-vue/docs/components/back-top/index.md
packages/devui-vue/docs/components/textarea/index.md
pnpm-lock.yaml

feat: BackTop组件新增滚动容器功能

---

packages/devui-theme/src/theme-collection/extend-theme.ts
packages/devui-vue/devui/image-preview/src/image-preview.scss

fix(ImagePreview): 优化ImagePreview组件样式

fix(ImagePreview): 优化ImagePreview组件样式

---

packages/devui-vue/devui/comment/__tests__/comment.spec.ts
packages/devui-vue/devui/tag-input/__tests__/tag-input.spec.ts

1. comment组件变动后修改单元测试
2. 修复 tag-input 单元测试错误

test(comment、tag-input): 单元测试变动

---

.github/workflows/pull-request.yml
packages/devui-vue/devui-cli/commands/code-check.js
packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/search/__tests__/search.spec.ts

- 增加全部组件通过单元测试的日志
- 修复search/date-picker-pro组件单元测试问题
- 增加单元测试的PR门禁

test: 修复search/date-picker-pro组件单元测试问题

---

packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/modal/src/composables/use-modal.ts

fix(Modal): 修复初始化v-model=true时，弹窗不显示问题

fix(Modal): 修复初始化v-model=true时，弹窗不显示问题

---

packages/devui-vue/devui/notification/src/notification-service.tsx
packages/devui-vue/devui/notification/src/notification.tsx
packages/devui-vue/devui/notification/src/use-notification.ts

fix(notification): 修复样式错误

---

packages/devui-vue/devui/message/__tests__/message.spec.tsx
packages/devui-vue/devui/message/index.ts
packages/devui-vue/devui/message/src/instance.tsx
packages/devui-vue/devui/message/src/message-icon-close.tsx
packages/devui-vue/devui/message/src/message-icons.tsx
packages/devui-vue/devui/message/src/message-service.tsx
packages/devui-vue/devui/message/src/message-types.ts
packages/devui-vue/devui/message/src/message.scss
packages/devui-vue/devui/message/src/message.tsx
packages/devui-vue/devui/styles-var/private/_font.scss
packages/devui-vue/devui/styles-var/private/_z-index.scss
packages/devui-vue/docs/components/message/index.md

add message component
often used for feedback after active operation.
The difference with Notification is that the latter is more used for passive Notification of system-level notifications.
This parameter is used when global prompt information needs to be displayed. The prompt information will disappear after several seconds.

feat: add message component

---

packages/devui-vue/devui/search/src/search.tsx

fix(Search): 组件内引入Icon，解决按需引入时Icon没有被解析的问题

fix(Search): 组件内引入Icon，解决按需引入时Icon没有被解析的问题

---

packages/devui-vue/devui/tree/src/composables/use-init-select-collection.ts
packages/devui-vue/devui/tree/src/composables/use-select.ts
packages/devui-vue/devui/tree/src/composables/use-tree-types.ts
packages/devui-vue/devui/tree/src/composables/utils.ts
packages/devui-vue/docs/components/tree/index.md

fix(Tree): 解决节点初始化选中时，点击其他节点不会取消选中的问题，补充treeFactory文档

fix(Tree): 解决节点初始化选中时，点击其他节点不会取消选中的问题，补充treeFactory文档

---

packages/devui-vue/devui/message/src/message-service.tsx
packages/devui-vue/devui/message/src/message.scss

- modify message type normal border color
- The default border color is changed to #575d6c

style(message): modify message type normal border color

---

packages/devui-vue/docs/components/message/index.md

- change message dome to setup mode

docs(message): change message dome to setup mode

---

packages/devui-vue/devui-cli/commands/release.js
packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
packages/devui-vue/package.json

update:
1. 更新组件的贡献者信息
2. `peerDependencies`中增加`"vue": "^3.2"`

docs: 更新贡献者信息

---

packages/devui-vue/docs/components/virtual-list/index.md

fix(VirtualList): 完善文档，补充item-height参数说明

fix(VirtualList): 完善文档，补充item-height参数说明

---

packages/devui-vue/devui/menu/index.ts
packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/menu.tsx

fix(menu): 修复组件闪烁问题

---

packages/devui-vue/devui/dropdown/src/use-dropdown.ts

fix(Dropdown): 修复展开时起始位置错误问题

---

packages/devui-vue/devui/cascader/components/cascader-item/index.scss

fix(Cascader): 修复禁用选项字体无禁用色问题

---

packages/devui-vue/docs/components/message/index.md

- modify the document title and other document styles

docs(message): modify the document title and other document styles

---

package.json
packages/devui-vue/devui/mention/index.ts
packages/devui-vue/devui/mention/src/mention-types.ts
packages/devui-vue/devui/mention/src/mention.scss
packages/devui-vue/devui/mention/src/mention.tsx
packages/devui-vue/devui/textarea/src/composables/use-textarea-event.ts
packages/devui-vue/devui/textarea/src/textarea.tsx
packages/devui-vue/docs/components/mention/index.md
pnpm-lock.yaml

feat: 完成Mention组件所有功能及文档和demo说明

feat: 完成Mention组件所有功能及文档和demo说明

---

packages/devui-vue/devui/table/src/table.tsx
packages/devui-vue/docs/components/table/index.md

fix(Table): 修复无法自适应宽度的问题

---

packages/devui-vue/docs/vite.config.ts
packages/devui-vue/tsconfig.json

feat: 增加vite @devui 路径别名配置

---

packages/devui-vue/devui/modal/src/modal.tsx

fix(Modal): 解决Modal组件默认情况下点击modal框内部关闭弹窗问题

---

packages/devui-vue/devui/cascader/hooks/use-cascader-style.ts
packages/devui-vue/devui/cascader/hooks/use-cascader.ts
packages/devui-vue/devui/cascader/src/cascader-types.ts
packages/devui-vue/devui/cascader/src/cascader.tsx
packages/devui-vue/docs/components/cascader/index.md

feat(Cascader): 增加host插槽，支持自定义展开菜单的宿主元素

feat(Cascader): 增加host插槽，支持自定义展开菜单的宿主元素

---

packages/devui-vue/devui/cascader/src/cascader.tsx

fix(Cascader): 处理Cascader组件可搜索功能异常

---

packages/devui-vue/devui/cascader/__tests__/cascader.spec.ts
packages/devui-vue/devui/cascader/hooks/use-cascader-popup.ts
packages/devui-vue/devui/cascader/hooks/use-cascader.ts
packages/devui-vue/devui/cascader/src/cascader-types.ts
packages/devui-vue/devui/cascader/src/cascader.tsx

fix(Cascader): 弹出面板移到body层，防止被父元素遮挡

fix(Cascader): 弹出面板移到body层，防止被父元素遮挡

---

packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
packages/devui-vue/devui/time-picker/src/time-picker.tsx
packages/devui-vue/devui/time-picker/src/types.ts

1、将弹出面板放到body层，解决被父元素遮挡的问题
2、移除输入框外层多余的div元素

fix(TimePicker): 将弹出面板放到body层，解决被父元素遮挡的问题

---

packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/month-picker.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/year-picker.spec.tsx
packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
packages/devui-vue/devui/date-picker-pro/src/composables/use-range-date-picker-pro.ts
packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
packages/devui-vue/devui/date-picker-pro/src/range-date-picker-types.ts
packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts

fix(DatePickerPro): 解决弹出面板为加到body层，导致被父元素隐藏的问题

fix(DatePickerPro): 解决弹出面板为加到body层，导致被父元素隐藏的问题

---

packages/devui-vue/devui/table/src/components/column/column.tsx

fix(Table): 修复数据结构层级较多时，渲染自定义模板失败的问题

fix(Table): 修复数据结构层级较多时，渲染自定义模板失败的问题

---

packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
packages/devui-vue/devui/select/__tests__/option-group.spec.tsx
packages/devui-vue/devui/select/__tests__/option.spec.tsx
packages/devui-vue/devui/select/__tests__/select.spec.tsx
packages/devui-vue/devui/select/src/select-types.ts
packages/devui-vue/devui/select/src/select.tsx
packages/devui-vue/devui/select/src/use-select.ts
packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
packages/devui-vue/docs/components/select/index.md

1、弹出面板未加到body层，导致面板位置不准确
2、移除输入框外层多余的div
3、改变浏览器窗口时，弹出面板的宽度不会自动调整

fix(Select): 解决使用过程中Select暴露出来的问题

---

packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/virtual-list/src/hooks/use-virtual.tsx

fix(VirtualList): 解决item-height参数值固定，导致数据量较少时无法滚动的问题

fix(VirtualList): 解决item-height参数值固定，导致数据量较少时无法滚动的问题

---

packages/devui-vue/docs/components/slider/index.md

1. 优化文档 demo 代码及数据结构错误
2. 文档中 input-number 组件样式异常问题

docs(slider): 优化文档 demo 代码及数据结构错误

---

packages/devui-vue/devui/menu/__tests__/menu.spec.ts
packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
packages/devui-vue/devui/menu/src/composables/use-nearest-menu-element.ts
packages/devui-vue/devui/menu/src/menu.scss
packages/devui-vue/devui/menu/src/menu.tsx
packages/devui-vue/devui/menu/src/styles/horizontal.scss
packages/devui-vue/devui/menu/src/styles/public.scss
packages/devui-vue/devui/menu/src/styles/vertical.scss
packages/devui-vue/docs/components/menu/index.md
packages/devui-vue/docs/en-US/components/menu/index.md

- 逻辑修复
- 修复溢出菜单中，router无法点击
- 修复溢出再显示后无法点击的bug
- 修复溢出菜单再显示，最后一个元素闪烁问题
- 单元测试
- 增加单元测试
- 样式修复
- 修复如果鼠标悬浮在任何一个menu-element上，同级的其他menu-element也会有hover的样式。
- 文档
- 添加 仅展开一项

fix(menu): 修复样式问题

---

packages/devui-vue/devui/cascader/hooks/use-cascader-style.ts
packages/devui-vue/devui/select/src/components/select-content.tsx

fix: 修改检视意见

---

packages/devui-vue/devui/switch/src/switch.scss
packages/devui-vue/docs/components/switch/index.md

style(switch): 调整Switch组件样式问题

---

packages/devui-vue/devui/menu/__tests__/menu.spec.ts
packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
packages/devui-vue/devui/menu/src/composables/use-nearest-menu-element.ts
packages/devui-vue/devui/menu/src/menu.scss
packages/devui-vue/devui/menu/src/menu.tsx
packages/devui-vue/devui/menu/src/styles/horizontal.scss
packages/devui-vue/devui/menu/src/styles/public.scss
packages/devui-vue/devui/menu/src/styles/vertical.scss
packages/devui-vue/docs/components/menu/index.md
packages/devui-vue/docs/en-US/components/menu/index.md

Reverts DevCloudFE/vue-devui#1161

Revert "fix(menu): 修复样式问题"

---

packages/devui-vue/devui/button/src/button.scss

Close #1183 
默认尺寸大小32px，每个尺寸大小相差4px大小

style(button): 修改Button按钮各尺寸大小

---

packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.tsx

test(tooltip): 修复 tooltip 测试用例偶现错误

---

.github/workflows/preview-build.yml
.github/workflows/pull-request.yml
package.json
pnpm-lock.yaml
scripts.json

This PR improves developers experience(DX) by adding `better-script` to introduce a new way of npm scripts writing.
Merge and Close #1186 .
Pain points:
- 😣 Too many scripts that hard to read and use
- 🧐 Need a way to reorganize those scripts
package.json
```json
"scripts": {
"dev": "pnpm --filter vue-devui dev",
"build": "pnpm --filter vue-devui build",
"build:lib": "pnpm --filter vue-devui build:lib",
"build:cli": "pnpm --filter devui-cli build",
"prepare": "husky install",
"precommit": "lint-staged",
"eslint": "eslint \"packages/**/{*.vue,*.js,*.ts,*.jsx,*.tsx}\"",
"eslint:fix": "eslint --fix \"packages/**/{*.vue,*.js,*.ts,*.jsx,*.tsx}\"",
"stylelint": "stylelint \"packages/**/{*.scss,*.css}\"",
"stylelint:fix": "stylelint --fix \"packages/**/{*.scss,*.css}\"",
"test": "pnpm --filter …
```

feat(root): add better-scripts

---

packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/modal/src/composables/useDraggable.ts
packages/devui-vue/devui/modal/src/modal-types.ts
packages/devui-vue/devui/modal/src/modal.scss
packages/devui-vue/devui/modal/src/modal.tsx
packages/devui-vue/docs/components/modal/index.md

feat: 完善modal组件功能及文档和demo说明

---

packages/devui-vue/docs/.vitepress/config/index.ts
packages/devui-vue/docs/.vitepress/devui-theme/components/AlgoliaSearchBox.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
packages/devui-vue/docs/.vitepress/devui-theme/components/PageToc.vue
pnpm-lock.yaml

效果如下：
点击输入框或者按`Ctrl+K`之后，弹出沉浸式搜索框

feat: add algolia search

---

packages/devui-vue/devui/switch/src/switch.scss
packages/devui-vue/docs/components/switch/index.md

style(switch): 修复小号的带自定义文字的switch组件样式问题

---

packages/devui-vue/devui/date-picker-pro/src/const.ts
packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
packages/devui-vue/devui/date-picker-pro/src/utils.ts

fix(date-picker-pro): 修复format为非法内容时日期显示异常的问题 closed #1153

---

packages/devui-vue/devui/select/src/use-select.ts

fix(Select): 下拉面板展开时更新位置

---

packages/devui-vue/devui/cascader/src/cascader.tsx

fix(Cascader): 修复在Drawer中使用时，选择之后Drawer异常关闭的问题

fix(Cascader): 修复在Drawer中使用时，选择之后Drawer异常关闭的问题

---

packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/composables/use-store.ts
packages/devui-vue/devui/menu/src/menu.tsx

fix(menu): 解决#1163

---

packages/devui-vue/devui/accordion/index.ts
packages/devui-vue/devui/button/__tests__/button.spec.tsx
packages/devui-vue/devui/drawer/__tests__/drawer.spec.tsx
packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx
packages/devui-vue/devui/icon/__tests__/icon.spec.ts
packages/devui-vue/devui/message/__tests__/message.spec.tsx
packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/notification/__tests__/notification.spec.tsx
packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
packages/devui-vue/devui/panel/__tests__/panel.spec.ts
packages/devui-vue/devui/panel/index.ts
packages/devui-vue/devui/popover/__tests__/popover.spec.tsx
packages/devui-vue/devui/result/__tests__/result.spec.ts
packages/devui-vue/devui/ripple/__tests__/ripple.spec.ts
packages/devui-vue/devui/search/__tests__/search.spec.ts
packages/devui-vue/devui/status/__tests__/status.spec.ts
packages/devui-vue/devui/status/index.ts
packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.tsx

test: add some it.todo

---

packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-event.ts
packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-function.ts
packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
packages/devui-vue/devui/tabs/src/components/tab/tab-types.ts
packages/devui-vue/devui/tabs/src/components/tab/tab.tsx
packages/devui-vue/devui/tabs/src/tabs-types.ts
packages/devui-vue/devui/tabs/src/tabs.tsx

fix(Tabs): 修复删除选项卡异常问题

---

packages/devui-vue/devui/tag/src/tag.scss
packages/devui-vue/docs/components/tag/index.md

fix(Tag): 移除容器外层多余marigin

---

packages/devui-vue/devui-cli/commands/code-check.js
packages/devui-vue/devui/checkbox/__tests__/checkbox.spec.ts
packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker/index.ts
packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
packages/devui-vue/devui/form/__tests__/form-item.spec.tsx
packages/devui-vue/devui/form/__tests__/form.spec.ts
packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
packages/devui-vue/devui/input/__tests__/input.spec.ts
packages/devui-vue/devui/layout/__tests__/layout.spec.ts
packages/devui-vue/devui/mention/__tests__/mention.spec.tsx
packages/devui-vue/devui/menu/__tests__/menu.spec.ts
packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
packages/devui-vue/devui/select/__tests__/select.spec.tsx
packages/devui-vue/devui/select/src/select-types.ts
packages/devui-vue/devui/select/src/use-select.ts
packages/devui-vue/devui/slider/__tests__/slider.spec.tsx
packages/devui-vue/devui/splitter/__tests__/splitter.spec.ts
packages/devui-vue/devui/switch/__tests__/switch.spec.ts
packages/devui-vue/devui/textarea/__tests__/textarea.spec.ts
packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
packages/devui-vue/devui/upload/__tests__/upload.spec.ts
packages/devui-vue/docs/components/time-picker/index.md

给数据录入和布局类组件增加`it.todo`单元测试待办标识

test: add test todo for data entry and layout components

---

packages/devui-vue/devui/cascader/src/cascader.tsx
packages/devui-vue/devui/dropdown/src/dropdown.tsx
packages/devui-vue/devui/dropdown/src/use-dropdown.ts
packages/devui-vue/devui/overlay/src/flexible-overlay/flexible-overlay-types.ts
packages/devui-vue/devui/overlay/src/flexible-overlay/index.tsx
packages/devui-vue/devui/popover/src/popover.tsx

fix(FlexibleOverlay): 在overlay阻止事件冒泡，防止弹出类组件和drawer等组合使用时，drawer异常关闭

fix(FlexibleOverlay): 在overlay阻止事件冒泡，防止弹出类组件和drawer等组合使用时，drawer异常关闭

---

packages/devui-vue/devui/select/src/use-select.ts

fix(Select): 修复新增选项时，面板位置错误问题

---

packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
packages/devui-vue/devui/table/src/components/column/column-types.ts
packages/devui-vue/devui/table/src/components/column/use-column.ts
packages/devui-vue/devui/table/src/components/fix-header.tsx
packages/devui-vue/devui/table/src/table.scss
packages/devui-vue/docs/components/table/index.md

fix(Table): 表头固定时，横向滚动表头需要跟随滚动；新增cell-class参数

fix(Table): 表头固定时,横向滚动表头需要跟随滚动；新增cell-class参数

---

packages/devui-vue/devui/tree/src/components/tree-node.tsx
packages/devui-vue/devui/tree/src/composables/use-dragdrop.ts
packages/devui-vue/devui/tree/src/composables/use-tree-types.ts
packages/devui-vue/docs/components/tree/index.md

fix(tree): cherry-pick PR1143 to fix tree dragdrop

---

packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
packages/devui-vue/devui/input-number/src/input-number-types.ts
packages/devui-vue/devui/input-number/src/input-number.scss
packages/devui-vue/devui/input-number/src/use-input-number.ts

1. 修正组件 size 的大小
2. 将设置 size 样式 class 作用于最外层容器
3. 修复操作按钮 会超出容器的bug, 之前滑块哪里出现过。
4. 修改测试用例

fix(input-number): 修正组件大小 及 修复操作按钮会超出容器的bug

---

packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/modal/src/composables/use-modal.ts
packages/devui-vue/devui/modal/src/modal.tsx

fix(Modal): 修复Modal异常关闭的问题

---

packages/devui-vue/docs/.vitepress/config/head.ts
packages/devui-vue/docs/.vitepress/devui-theme/index.js

修复 icon 字体文件加载失败，导致icon组件显示异常，看起来和url解析有关， 通过unpkg直接引入css样式绕过解析🤪

fix(icon): icon 字体文件加载失败，导致icon组件显示异常

---

packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/styles-var/devui-var.scss
packages/devui-vue/devui/styles-var/private/_size.scss

style(input): input组件的 size 大小

---

packages/devui-vue/devui/button/src/button.scss
packages/devui-vue/docs/components/button/index.md

fix(button): 修改图标按钮尺寸大小不一的情况

---

packages/devui-vue/devui/select/src/components/option.tsx
packages/devui-vue/devui/select/src/components/select-content.tsx
packages/devui-vue/devui/select/src/select.scss
packages/devui-vue/devui/select/src/use-select.ts

fix(Select): 解决多选双向绑定问题

---

packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/devui/table/src/components/body/body.tsx
packages/devui-vue/devui/table/src/components/fix-header.tsx
packages/devui-vue/devui/table/src/components/header/header.scss
packages/devui-vue/devui/table/src/components/header/header.tsx
packages/devui-vue/devui/table/src/composables/use-horizontal-scroll.ts
packages/devui-vue/devui/table/src/composables/use-table-types.ts
packages/devui-vue/devui/table/src/table.tsx

fix(Table): 滚动时固定列显示阴影

---

packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
packages/devui-vue/devui/table/src/composables/use-sort.ts
packages/devui-vue/devui/table/src/composables/use-table-types.ts
packages/devui-vue/devui/table/src/store/index.ts
packages/devui-vue/devui/table/src/store/store-types.ts

refactor(Table): 解决初始排序错误问题&优化排序代码

refactor(Table): 解决初始排序错误问题&优化排序代码

---

packages/devui-vue/devui/search/src/search-types.ts
packages/devui-vue/devui/select/src/select.scss
packages/devui-vue/devui/time-select/src/time-select.tsx
packages/devui-vue/docs/.vitepress/devui-theme/styles/demo-block.scss
packages/devui-vue/docs/components/alert/index.md
packages/devui-vue/docs/components/auto-complete/index.md
packages/devui-vue/docs/components/cascader/index.md
packages/devui-vue/docs/components/date-picker/index.md
packages/devui-vue/docs/components/dropdown/index.md
packages/devui-vue/docs/components/loading/index.md
packages/devui-vue/docs/components/modal/index.md
packages/devui-vue/docs/components/radio/index.md
packages/devui-vue/docs/components/search/index.md
packages/devui-vue/docs/components/select/index.md
packages/devui-vue/docs/components/steps/index.md
packages/devui-vue/docs/components/switch/index.md
packages/devui-vue/docs/components/table/index.md
packages/devui-vue/docs/components/textarea/index.md
packages/devui-vue/docs/components/time-picker/index.md
packages/devui-vue/docs/components/time-select/index.md
packages/devui-vue/docs/components/tooltip/index.md
packages/devui-vue/docs/components/transfer/index.md
packages/devui-vue/docs/components/tree/index.md

使用[devui设计规范](https://devui.design/design-cn/start)标准化devui文档

docs: standardized devui style

---

packages/devui-vue/devui/drawer/__tests__/drawer.spec.tsx
packages/devui-vue/devui/drawer/src/drawer-types.ts
packages/devui-vue/devui/drawer/src/drawer.tsx
packages/devui-vue/devui/drawer/src/use-drawer.ts
packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/modal/src/composables/use-modal.ts
packages/devui-vue/devui/modal/src/modal-types.ts
packages/devui-vue/devui/modal/src/modal.scss
packages/devui-vue/devui/modal/src/modal.tsx

fix: 修复Modal和Drawer同时使用异常关闭的问题

fix: 修复Modal和Drawer同时使用异常关闭的问题

---

packages/devui-vue/devui/select/src/use-select.ts

fix(Select): 修复筛选时面板位置错误问题

---

packages/devui-vue/devui/table/src/composables/use-table.ts
packages/devui-vue/docs/components/table/index.md

fix(Table): 修复列和数据都是异步渲染时，数据渲染失败的问题

fix(Table): 修复列和数据都是异步渲染时，数据渲染失败的问题

---

packages/devui-vue/devui/cascader/hooks/use-cascader.ts

fix(Cascader): 修复动态设置options失效的问题

fix(Cascader): 修复动态设置options失效的问题

---

packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx

增加对DatePickerPro的disabled属性的测试

test(date-picker-pro): disabled prop

---

packages/devui-vue/devui/checkbox/src/checkbox-group.scss
packages/devui-vue/devui/form/src/components/form-control/form-control.scss
packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/radio/src/radio-group.scss
packages/devui-vue/devui/textarea/src/textarea.tsx
packages/devui-vue/docs/components/form/index.md
packages/devui-vue/package.json
pnpm-lock.yaml

fix: Input和Textarea默认100%宽度

---

packages/devui-vue/devui/tree/src/tree.scss
packages/devui-vue/devui/tree/src/tree.tsx
packages/devui-vue/docs/components/tree/index.md

feat(Tree): 增加收起展开动画效果

---

packages/devui-vue/devui/search/src/search.scss

fix(Search): 刷新无边框样式

---

packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
packages/devui-vue/devui/time-picker/src/components/popup-line/popup-line-types.ts
packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
packages/devui-vue/devui/time-picker/src/components/time-popup/time-popup-types.ts
packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts

fix(TimePicker): 修复回显数据与format格式不一致问题

fix(TimePicker): 修复回显数据与format格式不一致问题

---

packages/devui-vue/devui/switch/__tests__/switch.spec.ts

test(switch): test color prop

---

packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
packages/devui-vue/devui/menu/index.ts
packages/devui-vue/docs/.vitepress/config/index.ts
packages/devui-vue/docs/on-demand/index.md

- move menu to navigation from layout
- fix on-demand doc header
- comment out algolia config

docs: fix docs problem

---

packages/devui-vue/devui/icon/src/icon.scss
packages/devui-vue/devui/icon/src/icon.tsx
packages/devui-vue/devui/input/src/input.scss
packages/devui-vue/devui/input/src/input.tsx

fix(Input): 优化不同size对应高度，解决清空图标显示问题

fix(Input): 优化不同size对应高度，解决清空图标显示问题

---

packages/devui-vue/devui/table/src/components/body/body.scss
packages/devui-vue/docs/components/table/index.md

fix(Table): 样式调整

---

packages/devui-vue/devui/search/src/search.scss

fix(Search): 无边框不设置背景色

---

packages/devui-vue/devui/notification/src/notification-service.tsx
packages/devui-vue/devui/notification/src/notification-types.ts
packages/devui-vue/devui/notification/src/notification.tsx
packages/devui-vue/devui/notification/src/use-notification.ts

fix(Notification): 修复鼠标移入后自动关闭失效的问题

fix(Notification): 修复鼠标移入后自动关闭失效的问题

---

packages/devui-vue/devui/select/src/use-select.ts

fix(select): 当输入带空格的文本，select搜索功能显示异常

---

packages/devui-vue/devui/mention/src/mention.tsx

fix(mention): Mention 提及组件，第一次选择后删除输入，第二次输入点击无法选中 close #1292

---

packages/devui-vue/devui/search/src/search.scss

+ 按照 issues 修改组件样式的大小
+ size、font-size 使用变量控制
+ icon 的大小与 font-size 保持一致，大小占位与size保持一致

style(search): 优化search 搜索框样式，统一组件不同size的大小 #1199

---

packages/devui-vue/devui/input/src/input.scss

style(input): input组件 size 大小使用scss变量向标准统一 #1199

---

packages/devui-vue/devui/dragdrop/src/droppable-directive.ts
packages/devui-vue/devui/dragdrop/src/sortable-directive.ts
packages/devui-vue/devui/dragdrop/src/utils.ts

fix(dragdrop): 修改可排序拖拽的bug

---

packages/devui-vue/devui/input/src/input.tsx

修复 input 组件绑定数据为 ref(null) 导致无法获取 length 的错误

fix(input): 修复 绑定数据为 ref(null) 导致无法获取 length 的错误 (close #1329)

---

packages/devui-vue/devui/auto-complete/src/auto-complete.scss
packages/devui-vue/docs/components/auto-complete/index.md

1. auto-complete 组件 size 大小使用scss变量向标准统一

style(auto-complete): auto-complete 组件 size 大小使用scss变量向标准统一 #1199

---

packages/devui-vue/devui/tag/src/tag-types.ts
packages/devui-vue/devui/tag/src/tag.scss
packages/devui-vue/docs/components/tag/index.md

1. 移除tag组件 size 属性 xs 类型，统一组件size类型
2. 更新文档、一些小修改
3. tag 组件可能不太适合其他组件的size，可以讨论下是否需要向其他组件统一🤔

fix(tag): 移除tag组件 size 属性 xs 类型，统一组件size类型 #1199

---

README.md
README.zh-CN.md
packages/devui-vue/docs/.vitepress/config/nav.ts
packages/devui-vue/docs/components/overview/feature-data.ts
packages/devui-vue/docs/components/overview/index.md
packages/devui-vue/docs/contributing/index.md

Update:
- Add maintainers in README
- Add join DevUI community in CONTRIBUTING.md

docs: add maintainers in README

---

packages/devui-vue/docs/components/radio/index.md

优化  radio-group 文档 根据条件终止切换操作示例

docs(radio-group): radio-group 根据条件终止切换操作示例，两个radio-group 没有间距

---

packages/devui-vue/devui/button/src/button.scss

修复button按钮在 “追光” 主题下 带icon按钮 icon颜色显示异常 ( [#1031 ](https://github.com/DevCloudFE/vue-devui/issues/1013))

fix(button): toggle theme button style questions

---

packages/devui-vue/docs/components/accordion/index.md

1. 使用内置路由和链接类型文档组件浮动导致展示问题
2. Accordion 事件表格展示问题

fix: #1236

---

packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.scss
packages/devui-vue/docs/components/accordion/index.md

fix(tabs): 修复在“追光” 主题下 options tabs 样式问题 close #1014

---

.github/workflows/auto-publish-npm.yml

chore(.github): 新增自动构建

---

packages/devui-vue/devui/mention/__tests__/mention.spec.tsx
packages/devui-vue/devui/mention/src/mention.tsx

1. 添加mention测试用例
2. 修改上次提交的作者信息

test(mention): 添加mention测试用例

---

packages/devui-vue/devui/checkbox/src/use-checkbox.ts

Signed-off-by: zhaoShijuan <18712788257@163.com>

fix(checkbox): 阻止事件冒泡，避免引发table中勾选时触发多个事件(#1446)

---

.github/workflows/auto-publish-npm.yml

fix: 修复自动化构建报错

---

packages/devui-vue/devui/message/src/message.scss
packages/devui-vue/devui/message/src/message.tsx

Signed-off-by: zhaoShijuan <18712788257@163.com>

fix(message)：修复duration为0时，移入移出自动关闭问题+修改关闭按钮不垂直居中样式(#1449)

---

packages/devui-vue/devui/popover/__tests__/popover.spec.tsx

1. 修改popover测试用例中存在的一些问题
2.  添加popvoer测试用例

test(popover): 添加popvoer测试用例

---

packages/devui-vue/docs/components/form/index.md

fix: 修复form组件文档校验出错 (#1454)

---

packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue

fix: theme props type warning

---

packages/devui-vue/devui/select/__tests__/select.spec.tsx
packages/devui-vue/devui/select/src/select-types.ts
packages/devui-vue/devui/select/src/use-select.ts

组件的 size > 表单的 size > 默认大小 md
更改后增加对size优先级的测试

fix(select): 修复 select 组件 size 属性的逻辑 （#1199）

---

packages/devui-vue/docs/.vitepress/devui-theme/components/AlgoliaSearchBox.vue

style(algolia): 组件文档 algolia 检索主题适配

---

packages/devui-vue/devui/cascader/__tests__/cascader.spec.ts
packages/devui-vue/devui/cascader/src/cascader-types.ts
packages/devui-vue/docs/components/cascader/index.md

1. cascader组件 props size 在表单内部时应该跟随表单变化
2. 增加 props size优先级测试用例
3. 文档增加 size 尺寸示例

cascader组件 props size 在表单内部时应该跟随表单变化

---

packages/devui-vue/devui/search/__tests__/search.spec.ts
packages/devui-vue/devui/search/src/composables/use-search-class.ts
packages/devui-vue/devui/search/src/search-types.ts
packages/devui-vue/devui/search/src/search.tsx
packages/devui-vue/docs/components/search/index.md

search 组件在 form 表单内部时 应该跟随表单的size变化

search 组件在 form 表单内部时 应该跟随表单的size变化

---

packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
packages/devui-vue/devui/input-number/src/input-number-types.ts
packages/devui-vue/devui/input-number/src/use-input-number.ts

1. input-number 组件在 form 内时根据表单 size 变化
2. 增加 props size 优先级测试

input-number 组件在 form 内时根据表单 size 变化

---

packages/devui-vue/docs/components/form/index.md

form 文档 size 示例，增加 timeSelect、timePicker，方便测试对照组件的大小。

form 文档 size 示例，增加 timeSelect、timePicker。

---

packages/devui-vue/devui/search/__tests__/search.spec.ts
packages/devui-vue/devui/search/src/search.tsx

1. fix props max-length
2. improve test case

search component： fix props max-length、 improve test case

---

packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
packages/devui-vue/docs/components/tabs/index.md

fix(tabs): fix content of tab has not changed when add a tab

---

packages/devui-vue/devui/collapse/src/collapse.scss

fix(collapse): 修复折叠面板禁用时图标颜色

---

packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts

fix(time-picker): fix test case not pass

---

README.md
README.zh-CN.md

Add @xiaogonggong-w, @hqchqc and @Lucky-Ya-Q for code.

docs: update contributors

---

.github/workflows/preview-build.yml
packages/devui-vue/docs/.vitepress/demo/Demo.vue
packages/devui-vue/docs/.vitepress/plugins/block-plugin.ts
packages/devui-vue/docs/.vitepress/plugins/md-transformer.ts
packages/devui-vue/docs/vite.config.ts
packages/devui-vue/package.json
pnpm-lock.yaml

fix: 修复文档构建错误

---

packages/devui-vue/docs/.vitepress/demo/Demo.vue

updatefile: Demo.vue. Change use vue file rendered code

fix: the demo description is not rendered #1534

---

packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
packages/devui-vue/devui/menu/src/menu.tsx
packages/devui-vue/docs/components/menu/index.md
pnpm-lock.yaml

fix: 修复default-select-keys无法响应式的问题 #1542

---

packages/devui-vue/devui/tag/src/tag.tsx

修复Tag标签primary类型选中状态下，关闭按钮颜色与背景色一致
[测试链接](https://devcloudfe.github.io/devui-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgPGRpdiBjbGFzcz1cInRhZy1kZW1vLXdyYXBwZXJcIj5cbiAgICA8ZC10YWcgZGVsZXRhYmxlIGNoZWNrZWQ+5qCH562+5LiAPC9kLXRhZz5cbiAgICA8ZC10YWcgdHlwZT1cInByaW1hcnlcIiBkZWxldGFibGUgY2hlY2tlZD7moIfnrb7kuow8L2QtdGFnPlxuICAgIDxkLXRhZyB0eXBlPVwic3VjY2Vzc1wiIGRlbGV0YWJsZSBjaGVja2VkPuagh+etvuS4iTwvZC10YWc+XG4gICAgPGQtdGFnIHR5cGU9XCJ3YXJuaW5nXCIgZGVsZXRhYmxlIGNoZWNrZWQ+5qCH562+5ZubPC9kLXRhZz5cbiAgICA8ZC10YWcgdHlwZT1cImRhbmdlclwiIGRlbGV0YWJsZSBjaGVja2VkPuagh+etvuS6lDwvZC10YWc+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNldHVwRGV2dWkgfSBmcm9tICcuL2RldnVpLmpzJ1xuXG4vLyBkb24ndCByZW1vdmVcbnNldHVwRGV2dWkoKVxuPC9zY3JpcHQ+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J …

fix(tag): 修复Tag标签primary类型选中状态下，关闭按钮颜色与背景色一致 (close #1539)

---

packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/modal/src/modal.tsx
packages/devui-vue/docs/components/modal/index.md

1. 描述： 在 `modal` 中得按钮添加 `autofocus` 自动聚焦按钮

feat: 弹窗中新增autofocus自动聚焦

---

README.md
README.zh-CN.md
packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
packages/devui-vue/devui/image-preview/src/image-preview-service.ts
packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
packages/devui-vue/devui/modal/src/modal.tsx
packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
packages/devui-vue/docs/components/modal/index.md
packages/devui-vue/package.json
packages/devui-vue/tsconfig.json
pnpm-lock.yaml

Reverts DevCloudFE/vue-devui#1562

Revert "release v1.5.4"

---

packages/devui-vue/devui/input/__tests__/input.spec.ts

add input conponent `validate-event` test case

feat(Input): add input `validate-event` test case

---

packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx

add input-number component `focus` `blur` `select` methods test case

feat(InputNumber): add`focus blur select`test case

---

packages/devui-vue/devui/drawer/__tests__/drawer.spec.tsx

add `Drawer` component `drawerService` test case

feat(Drawer): add `drawerService` test case

---

packages/devui-vue/devui/select/src/use-select.ts
pnpm-lock.yaml

fix: 修复select组件清空时不清空filterQuery的问题

---

packages/devui-vue/devui/breadcrumb/index.ts

feat(Breadcrumb): 新增面包屑组件

---

packages/devui-vue/devui/code-editor/index.ts
packages/devui-vue/devui/code-editor/src/code-editor-types.ts
packages/devui-vue/devui/code-editor/src/code-editor.scss
packages/devui-vue/devui/code-editor/src/code-editor.tsx
packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
packages/devui-vue/docs/components/code-editor/index.md
packages/devui-vue/package.json
pnpm-lock.yaml

feat: 添加codeEditor组件

---

packages/devui-vue/devui-cli/shared/constant.js
packages/devui-vue/devui/action-timeline/index.ts
packages/devui-vue/devui/action-timeline/src/action-timeline-types.ts
packages/devui-vue/devui/action-timeline/src/action-timeline.scss
packages/devui-vue/devui/action-timeline/src/action-timeline.tsx
packages/devui-vue/docs/components/action-timeline/index.md
packages/devui-vue/docs/components/code-editor/index.md

feat(ActionTimeline): 新增操作时间轴组件

feat(ActionTimeline): 新增操作时间轴组件

---

packages/devui-vue/devui/button/src/button-types.ts
packages/devui-vue/devui/button/src/button.tsx
packages/devui-vue/devui/pagination/src/pagination-types.ts
packages/devui-vue/devui/pagination/src/pagination.tsx
packages/devui-vue/docs/components/button/index.md
packages/devui-vue/docs/components/pagination/index.md
packages/devui-vue/package.json

* feat(button): 按钮增加nativeType参数
* feat(pagniation): 增加最大分页数参数
* feat(pagniation): 版本号修改
* feat(pagniation): 检视意见修复
---------

feat(button&pagniation): 按钮增加nativeType参数&&pagniation增加最大分页数参数 (#1748)

---

packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
packages/devui-vue/devui/form/src/form-types.ts
packages/devui-vue/package.json

* fix: 修复form按模块打包symbol造成inject token不一致问题

fix: 修复form按模块打包symbol造成inject token不一致问题 (#1785)

---

packages/devui-vue/devui/dropdown/src/dropdown.tsx
packages/devui-vue/devui/dropdown/src/use-dropdown.ts
packages/devui-vue/devui/editable-select/src/components/dropdown/dropdown.tsx
packages/devui-vue/package.json

fix(Dropdown): 修改展开位置在下方时，关闭动画异常问题
fix(EditableSelect): 远程搜索时，loading结束再显示无数据

fix(Dropdown): 修改展开位置在下方时，关闭动画异常问题

---

packages/devui-vue/devui/category-search/src/components/text-input-menu.tsx

fix: 组件易用性优化，category-search组件唤出textInput时，input框自动聚焦 (#1842)

---

packages/devui-vue/devui/tree/src/composables/use-tree-node.ts

给树形控件子节点 devui-tree__node添加选中的类名

feat(tree):树形控件选中节点添加选中类名 #1880

---

packages/devui-vue/devui/code-review/src/code-review-types.ts
packages/devui-vue/devui/code-review/src/code-review.tsx
packages/devui-vue/devui/code-review/src/composables/use-code-review-comment.ts
packages/devui-vue/devui/code-review/src/composables/use-code-review-expand.ts
packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
packages/devui-vue/devui/code-review/src/utils.ts
packages/devui-vue/docs/components/code-review/index.md
packages/devui-vue/package.json

* feat(CodeReview): 支持传入options&暴露清除选中行样式的方法

feat(CodeReview): 支持传入options&暴露清除选中行样式的方法 (#1912)

---

packages/devui-vue/devui/code-review/src/composables/use-code-review-comment.ts
packages/devui-vue/devui/code-review/src/composables/use-code-review-line-selection.ts
packages/devui-vue/package.json

* fix(CodeReview): 修复拖拽时记录的行号区间错误的问题

Xingyan/fix code review (#1916)

---

packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
packages/devui-vue/package.json

fix(CodeReview): 选中文字后，再点击输入框时，输入框无法获取焦点

fix(CodeReview): 选中文字后，再点击输入框时，输入框无法获取焦点
